### ISSUE TITLE
Potential inter-mod conflict with Botania

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/FoamFix#1]
First of all, thanks alot for making FoamFix!
The issue I ran into is that, after installing FoamFix into [Skyexchange 1.2.3](https://minecraft.curseforge.com/projects/skyexchange/files/2338737), all of my floating flowers from Botania have weird model, which, I swear, that has never seen before until today I install FoamFix (last time I opened this pack was weeks ago), as shown by following screenshots:

A munchdew:
![2016-11-24_10 37 12](https://cloud.githubusercontent.com/assets/9113033/20604081/900f30ea-b232-11e6-958a-0c395ad644d6.png)
A hopperhock:
![2016-11-24_10 37 27](https://cloud.githubusercontent.com/assets/9113033/20604071/80d7fe36-b232-11e6-864b-4ffbe83c3920.png)
Another hopperhock:
![2016-11-24_10 37 39](https://cloud.githubusercontent.com/assets/9113033/20604072/80d858ae-b232-11e6-8de2-0e6a86682086.png)
Yet another hopperhock:
![2016-11-24_10 38 29](https://cloud.githubusercontent.com/assets/9113033/20604073/80d97afe-b232-11e6-9960-7011410549ee.png)

The version of botania I am using is r1.9-333. MinecraftForge version is 12.18.2.2121.
@TartaricAcid can replicate the same issue within Botania r1-.9-339, which is the latest version of Botania.

Since I am not sure abuot the cause of this issue, I figure that I need also ping @Vazkii

**Comment by asiekierka** [comment]
Main question: Does it happen with just Botania installed? If yes, the simple solution is to blacklist Botania's flower models from being handled by the deduplicator until a suitable solution is found - I should be able to add a config option for this into 0.3.2.

**Comment by 3TUSK** [comment]
Confirmed that the same issue happens with just Botania r1.9-239 (incl. Baubles and AutoRegLib as required library) and FoamFix. MinecraftForge version is 12.18.2.2151 which is the latest.
![2016-11-24_13 39 36](https://cloud.githubusercontent.com/assets/9113033/20608038/b1fb247a-b24b-11e6-9876-d10cc4624646.png)

**Comment by asiekierka** [comment]
Fixed in 0.3.2.

**Comment by asiekierka** [comment]
No. That was incorrect. Worked around in 0.3.2.

We're getting this fixed. One day.

**Comment by 3TUSK** [comment]
> *Surprise! A wild issue revived*

**Comment by asiekierka** [comment]
0.9.x series brings back the optimization. Closed and fixed. :)
