### ISSUE TITLE
FoamFix enableCoremodDeduplicator doesn't like being a thing

### ISSUE THREAD

**Issue by darkshadow1809** [asiekierka/FoamFix#10]
http://pastebin.com/sQiubdrf

On load crash.

Foamfix 4.1 Anarchy edition.

EDIT: works with Foamfix 0.4.0a Anarchy Edition

**Comment by asiekierka** [comment]
Try 0.4.1a.

**Comment by darkshadow1809** [comment]
Yep you fixed it! Thanks for the fast fix 👍  Also on the new update i seemed to have dropped 500 MB in ram? give or take. Don't know if its your doing but if it is thanks again ;) !
