### ISSUE TITLE
[1.12.2] Ender Chest Crash (possible mod incompatability)

### ISSUE THREAD

**Issue by Cynosphere** [asiekierka/FoamFix#100]
[Crash Report](https://hastebin.com/doxiwadacu)
[Mod List](https://i.braixen.party/9r34fizy.png)

Possibly incompatible with my anti-GC ASM hack of my tweak mod (or mass amount of coremods that touch various things), if so, sorry for the invalid report.

The anti-GC ASM hack is the same found in prplz's performance mod for 1.8

**Comment by asiekierka** [comment]
This version of OptiFine is incompatible with latest versions of Forge.
