### ISSUE TITLE
Foamfix causes `TileEntity.getKey(TileEntityHopper.class)` to return null

### ISSUE THREAD

**Issue by Robijnvogel** [asiekierka/FoamFix#105]
This is unexpected behaviour.
See https://github.com/DimensionalDevelopment/DimDoors/issues/36#issuecomment-358874858

We could technically write specific compatibility for your `TileEntityFasterHopper`, however I personally think that it's better to solve the issue at its root.
What can you do?

**Comment by asiekierka** [comment]
Ugly hacks which may break compatibility with something but should work fine.

**Comment by asiekierka** [comment]
Specifically, make TileEntityHopper return the same key as TileEntityFasterHopper, but always instantiate the latter.

**Comment by Robijnvogel** [comment]
@asiekierka that sounds just like the ASM-level hackery that we need. :)

**Comment by Robijnvogel** [comment]
Is this released yet? (seems not, latest release was 12th of January?)
If not, please give us a headsup when it is, okay?

**Comment by asiekierka** [comment]
Tomorrow at the latest, as I'll be very busy after then.

**Comment by asiekierka** [comment]
Alternatively, you can disable "fasterHopper" for the time being.

**Comment by asiekierka** [comment]
https://asie.pl/files/mods/FoamFix/foamfix-0.8.5-1.12.2-anarchy.jar

**Comment by Robijnvogel** [comment]
```Alternatively, you can disable "fasterHopper" for the time being.```
I know. :)
And now so does everyone else who reads this.

**Comment by asiekierka** [comment]
Well, 0.8.5 is out so you no longer have to. Enjoy!

**Comment by Robijnvogel** [comment]
Yay!

**Comment by Robijnvogel** [comment]
@asiekierka it didn't work. We still have the same crash and it only happens for Hoppers.
Not for signs, note blocks, dispensers, comparators, furnaces or chests, which are the other TileEntities that we use this code for.
https://pastebin.com/rBuzMMZu

We will implement a workaround for now, but please do fix this, okay?

**Comment by asiekierka** [comment]
@Robijnvogel 

>System.out.println(TileEntity.getKey(TileEntityHopper.class));

On FoamFix 0.8.5, this seems to return "minecraft:hopper". Are you sure?

**Comment by Robijnvogel** [comment]
Have you tested that out-of-dev?
If I add FoamFix to the `/run/mods` folder of my dev environment, it comes up with other errors that probably have nothing to do with this. As such, I have only been able to test DimDoors + FoamFix in the field.

All I can do right now is point you to [our code](https://github.com/DimensionalDevelopment/DimDoors/blob/1.12-WIP/src/main/java/org/dimdev/dimdoors/shared/tools/SchematicConverter.java#L406). And ask you to test FoamFix with [our latest release](https://github.com/DimensionalDevelopment/DimDoors/releases/latest). (look at the log spam :P)

PS. I am using FoamFix **Anarchy** 0.8.5, by the way.

**Comment by asiekierka** [comment]
To add it to the dev environment, you first need to manually run it through the BON2 deobfuscator.

I'll have a look.

**Comment by asiekierka** [comment]
Okay, yeah, I messed up, 0.8.6 will actually fix this.

**Comment by asiekierka** [comment]
https://asie.pl/files/mods/FoamFix/foamfix-0.9.0-1.12.2-anarchy.jar

please please tell me i got this one right

**Comment by Robijnvogel** [comment]
I see no errors in my log. :D
Looks like it's fixed!

**Comment by Robijnvogel** [comment]
Also, @asiekierka it has been a pleasure doing business with you. :)
I hope we'll meet again under more... _favourable_ circumstances.

**Comment by asiekierka** [comment]
This wasn't _that_ unfavorable. Good luck with DimDoors!

**Comment by Robijnvogel** [comment]
Also, we are probably going to extract the code that used to conflict with FoamFix to an external tool, since it was just meant to convert some Minecraft 1.6.4 assets into MC 1.10+ assets. :P Take care!

**Comment by asiekierka** [comment]
Doesn't matter - what you found is an inconsistency in behaviour relative to vanilla, even if it's a very obscure one which will likely remain unused by most modders. So it was still a bug! :)
