### ISSUE TITLE
AMD card detection doesn't really work right on 'older' cards

### ISSUE THREAD

**Issue by Kobata** [asiekierka/FoamFix#106]
Apparently even up to the R9 2xx series (at minimum), which are marked AMD physically, the driver decides to use the older vendor:
`	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13506 Compatibility Profile Context 23.20.15002.11' Renderer: 'AMD Radeon R9 200 Series'`

E: I went searching and it appears even the newest ones use ATI vendor, at least on windows: http://opengl.gpuinfo.org/gl_generatereport.php?reportID=2272

**Comment by asiekierka** [comment]
Yes, I could only really verify on Linux myself.

Thanks! I will fix it, although I am quite busy for the next two weeks. Thanks for the original patch as well!
