### ISSUE TITLE
[1.12] Crash with BiblioCraft

### ISSUE THREAD

**Issue by MasterEnderman** [asiekierka/FoamFix#107]
Crash-Report: https://pastebin.com/2aN7BDXD
FoamFix: 0.8.4-anarchy
BiblioCraft: 2.4.3
Forge: 14.23.1.2602

**Comment by asiekierka** [comment]
Could you please test without FoamFix?

**Comment by MasterEnderman** [comment]
doesn't happen without foamfix. it works fine after i disabled 

```
 # Replaces the default BlockState/ExtendedBlockState implementations with a far more memory-efficient variant. [default: true]
    B:smallPropertyStorage=false
```

**Comment by asiekierka** [comment]
Finally! An actual crash related to this feature.

Could you send me reproduction steps? I will have a look ASAP.

**Comment by MasterEnderman** [comment]
i just placed down a framed armor stand from bibliocraft after filling it with a slate block from rustic. then i put some iron armor on it and as i turned away from it it crashes. thats basically all i have.

also i've noticed something else with bibliocraft and foamfix. After i cut down a tree with tree chopper all bibliocraft blocks will face north and won't show their inventory until you open them and put an item out of the block and put it back in. But I'm not sure if this is caused by the same feature in foamfix.

**Comment by asiekierka** [comment]
Seems to work fine for me. Does the same happen with FoamFix 0.9.0?

**Comment by MasterEnderman** [comment]
I'll update later today and will tell you again if something breaks.

**Comment by MasterEnderman** [comment]
Updated and turned the config option back on. No crash yet.
