### ISSUE TITLE
FoamFix 0.9.3 causes IndexOutOfBounds on startup

### ISSUE THREAD

**Issue by ichttt** [asiekierka/FoamFix#112]
See https://pastebin.com/3iWqSgdN.
Did work in 0.9.1 and 0.9.2, seems to be a problem with the property value mapper

**Comment by asiekierka** [comment]
Does 0.9.2 work fine?

**Comment by ichttt** [comment]
Yes, just started up the modpack with 0.9.2 and it isn't crashing

**Comment by asiekierka** [comment]
Just let Una know to pull 0.9.3, have done likewise on my mod mirror.

Downgrade to 0.9.2 for now.
