### ISSUE TITLE
MPUtils Incompatibility on 0.9.3 [1.12.2]

### ISSUE THREAD

**Issue by CDAGaming** [asiekierka/FoamFix#116]
[crash-2018-02-01_10.25.31-client.txt](https://github.com/asiekierka/FoamFix/files/1686284/crash-2018-02-01_10.25.31-client.txt)

Seems to be on FoamFix side I think, as without it it does work fine.

**Comment by asiekierka** [comment]
Don't use 0.9.3. Why are you using 0.9.3? Stop using that.

**Comment by asiekierka** [comment]
As for the error, *how* does that even happen I don't even think it's FoamFix-related I don't touch anything remotely related

**Comment by CDAGaming** [comment]
It occurs when the game loads up. And I saw it up on Unu's page, though i saw it got removed. Will try 0.9.2

**Comment by CDAGaming** [comment]
Yup 0.9.3 is the only version this issue occurs, 0.9.2 works fine. Adjusting Title.

**Comment by asiekierka** [comment]
Yes, it was up, but it was quickly taken down as it was impressively broken.

**Comment by CDAGaming** [comment]
Ah, Ok. In that case, I look forward to your next Update.
