### ISSUE TITLE
Weird bed duplication bug

### ISSUE THREAD

**Issue by herobrine150400** [asiekierka/FoamFix#118]
I've installed FoamFix 0.9.2 for Minecraft 1.12.2, and if I try to break a bed, a weird bug happens:

If I break the head of the bed (the part with the white texture), it drops a bed of the correct colour, but it doesn't break the other side of the bed, which, if I break after, won't drop anything.

But if I break the other side of the bed first, it drops a red bed (regardless of the colour of it), while also not breaking the head, then, if I break the head, it drops **ANOTHER** bed, this time with the correct colour.

I was using Forge 14.23.1.2587, I tried to update it to version 14.23.1.2610, but it still happens. I have this issue even with only FoamFix installed.

This happens with FoamFix 0.9.2 installed, but it doesn't with FoamFix 0.8.1 (both Lawful and Anarchy).

For now, I'll just use FoamFix 0.8.1, but this bug is really annoying.

**Comment by asiekierka** [comment]
Could you disable ghostbuster.patchBeds and try again?

**Comment by herobrine150400** [comment]
Now the beds work properly, thanks! 👍

**Comment by asiekierka** [comment]
... How.

**Comment by herobrine150400** [comment]
Uh... they just... work as they should...
is this weird? :|

**Comment by asiekierka** [comment]
How does my patch break this.

**Comment by asiekierka** [comment]
Oh. Nevermind. Got it.

**Comment by asiekierka** [comment]
This will be fixed in the next release.

**Comment by herobrine150400** [comment]
Thanks! 😄 
I really like this mod! Minecraft was using lots of RAM and lagging a lot, and this mod fixed it.
