### ISSUE TITLE
(Bug report with my wallet) No money is appearing!!

### ISSUE THREAD

**Issue by NarigudoBR** [asiekierka/FoamFix#12]
but thanks to your mod that's not a huge problem :p (RAM is not that cheap in Brazil!!)

**Comment by asiekierka** [comment]
FoamFix is not supposed to provide you additional money, but prevent it from mysteriously disappearing.

**Comment by NarigudoBR** [comment]
I know :p, it's just a kidding!! but the mod is really great!!! saved me some precious RAM!!
