### ISSUE TITLE
You know what, I'm not sure where to put this weird bug

### ISSUE THREAD

**Issue by Sunconure11** [asiekierka/FoamFix#120]
https://pastebin.com/vBWnupeB

**Comment by asiekierka** [comment]
Most likely a Blood Magic bug. Try without FoamFix.

**Comment by ChloeDawn** [comment]
TehNut messed up in his BloodMagic compat PR to Chisel. He has int loops for getStateFromMeta that reach 16.

**Comment by asiekierka** [comment]
Is he aware?

**Comment by ChloeDawn** [comment]
I've pinged him about it, he'll see when he wakes up. I've let tterrag know too since the PR was merged and the fix can be on Chisel's end.
