### ISSUE TITLE
Virus detected upon attempting to download from https://unascribed.com/foamfix/

### ISSUE THREAD

**Issue by donoya** [asiekierka/FoamFix#121]
Am I downloading from the wrong site? Is the file safe in another? Has the mod been Compromised? Or is my antivirus giving a false alarm? I'm using McAfee, if that helps you.

**Comment by EverNife** [comment]
Small sugestion, use kaspersky... (It has a free version too)

Else, use this site to be 100% sure https://www.virustotal.com/pt/

(I downloaded my version from there, no problems :D _)

**Comment by asiekierka** [comment]
The mod is signed, any tampering with the JAR will cause a signature mismatch - you can use jarsigner to check, I think?
