### ISSUE TITLE
Bed Patch Causing Drop Duplication

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/FoamFix#126]
The bed patch in FoamFix isn't correctly notifying the other half of the bed when broken by a player in survival, and results in an additional bed being dropped, due to additional logic in the BlockBed class. 

**FoamFix version:** [1.12.2-0.9.4-Anarchy](https://unascribed.com/foamfix/FoamFix-1.12.2-0.9.4-Anarchy.jar)

**Comment by asiekierka** [comment]
Could not reproduce on 0.9.4; can reproduce on 0.9.2.

**Comment by asiekierka** [comment]
Can you still reproduce it on latest FoamFix/
