### ISSUE TITLE
Modpack Support

### ISSUE THREAD

**Issue by xlxAciDxlx** [asiekierka/FoamFix#13]
Sorry if I missed something, but I was wondering if you allow your mod to be included in modpacks? If so, can you either upload it to Curse or at least put somewhere that we have the permission to include the file in our modpacks so I can add it to Curse's allowed mod list? Thanks :)

**Comment by asiekierka** [comment]
1. Yes, it's GPLv3.
2. Sorry, I am currently not planning to upload it to Curse.
3. Just link them to the LICENSE file. The Curse folk know me well by now, I think.

**Comment by xlxAciDxlx** [comment]
Okay, I just wanted to make sure it was okay with you to include it. Thank you :)
