### ISSUE TITLE
Tinkers Issues?

### ISSUE THREAD

**Issue by Drakoflame** [asiekierka/FoamFix#130]
When I used this mod, I noticed that some tinkers tools (added by Construct's Armory, an armor mod for Tcon, and PlusTic) didn't have any colors, IIRC some of Tinkers own Tools didn't have any colors to them and appeared white, and have no colors.... I don't know what happened, I don't know how I can help, what else I can do to help with the issue, it really did help with my memory issues, at least until I can get more RAM for my laptop!

**Comment by asiekierka** [comment]
[Could not reproduce.](https://img.asie.pl/Q6ll) Are you sure it's not another mod?

**Comment by Drakoflame** [comment]
Hmm (sorry about late reply), could maybe it have something to do with Optifine as well? I have over 130 mods installed and while yes, I could disable them one by one to see what causes it, that would take an ungodly ammount of time (as I only have 8 gigs of RAM on my new laptop, and I have 4 dedicated to minecraft, It takes forever for MC to boot up, and was hoping this mods would allow me to keep firefox>pandora open while I played, but to no avail).

**Comment by asiekierka** [comment]
Possible! Try without OptiFine.

**Comment by collwee** [comment]
if you have the mod TexFix remove it. i was also having this problem.

**Comment by asiekierka** [comment]
Next time, please post your mod list too.
