### ISSUE TITLE
instant crashes in the atm3 modpack

### ISSUE THREAD

**Issue by acidjazz** [asiekierka/FoamFix#133]
check out the last 5 crash reports here https://gist.github.com/acidjazz

if i remove foamfix from the mods folder it works fine

**Comment by asiekierka** [comment]
Please try disabling experimental.cheapMinimumLight. What is your Smooth Lighting option set to?

**Comment by acidjazz** [comment]
No idea, I've never messed with any settings, just a couple keybindings.

**Comment by asiekierka** [comment]
Did you try disabling that setting in config/foamfix.cfg?

**Comment by MechanosG** [comment]
I get a lot of these tesselating block model crashes too.  With newer versions of forge, it happens immediately if I try to break any blocks.  If I go back to forge 14.23.2.2650, I can break blocks again.  But eventually I still end up getting the error.  I'm not 100% certain I have the same issue as OP, but I'm getting a very similar error in the crash log, and I just happened to have minimum set on smooth lighting.

I'll try turning off the experimental setting in foamfix and see what happens.

**Comment by MechanosG** [comment]
With that setting turned off, I haven't had a single crash yet.  Fingers crossed.  I'm glad I found this issue posted.

**Comment by asiekierka** [comment]
See #143
