### ISSUE TITLE
0.9.6 1.12.2 Anarchy Crash

### ISSUE THREAD

**Issue by ElSaam** [asiekierka/FoamFix#134]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.2-1.12.2.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  SignPictureCorePlugin (SignPicture-1.12.1-2.8.1-universal.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.5-core.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.6-1.12.2-anarchy.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  CreativePatchingLoader (CreativeCore_v1.9.19_mc1.12.2.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.169.jar)
  ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 4/5/18 5:33 PM
Description: Initializing game

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.isIdentity()Z
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:444)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:193)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:816)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:642)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.isIdentity()Z
	at pl.asie.foamfix.client.FoamyItemLayerModel.bakeStatic(FoamyItemLayerModel.java:335)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:80)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bakeImpl(ModelLoader.java:471)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:841)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader$1.load(ModelLoader.java:837)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:444)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:193)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:816)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:642)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6128567920 bytes (5844 MB) / 8525971456 bytes (8131 MB) up to 8525971456 bytes (8131 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -Xms8G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 Optifine OptiFine_1.12.2_HD_U_C9 95 mods loaded, 95 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                           | Signature                                |
	|:----- |:-------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCH   | mcp                  | 9.42                     | minecraft.jar                                    | None                                     |
	| UCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.2.2624.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.2.2624             | forge-1.12.2-14.23.2.2624.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | creativecoredummy    | 1.0.0                    | minecraft.jar                                    | None                                     |
	| UCH   | itemphysic           | 1.4.0                    | minecraft.jar                                    | None                                     |
	| UCH   | micdoodlecore        |                          | minecraft.jar                                    | None                                     |
	| UCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                    | None                                     |
	| UCH   | obfuscate            | 0.2.2                    | minecraft.jar                                    | None                                     |
	| UCH   | elucore              | 1.0                      | minecraft.jar                                    | None                                     |
	| UCH   | mercurius_updater    | 1.0                      | MercuriusUpdater-1.12.2.jar                      | None                                     |
	| UCH   | aether_legacy        | 1.12.2-v2.0              | aether_legacy-1.12.2-v2.0.jar                    | None                                     |
	| UCH   | biomesoplenty        | 7.0.1.2334               | BiomesOPlenty-1.12.2-7.0.1.2334-universal.jar    | None                                     |
	| UCH   | craftstudioapi       | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar            | None                                     |
	| UCH   | animania             | 1.4.7                    | animania-1.12.2-1.4.7.jar                        | None                                     |
	| UCH   | architecturecraft    | @VERSION@                | architecturecraft-1.12-2.68.jar                  | None                                     |
	| UCH   | codechickenlib       | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux         | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | brandonscore         | 2.4.0                    | BrandonsCore-1.12-2.4.0.152-universal.jar        | None                                     |
	| UCH   | buildcraftlib        | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftcore       | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftbuilders   | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftenergy     | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftfactory    | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftrobotics   | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcraftsilicon    | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | buildcrafttransport  | 7.99.15                  | buildcraft-7.99.15.jar                           | None                                     |
	| UCH   | camera               | 1.0.2                    | camera-1.0.2.jar                                 | None                                     |
	| UCH   | chiselsandbits       | 14.16                    | chiselsandbits-14.16.jar                         | None                                     |
	| UCH   | cofhcore             | 4.3.10                   | CoFHCore-1.12.2-4.3.10.5-universal.jar           | None                                     |
	| UCH   | cofhworld            | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar          | None                                     |
	| UCH   | extendedrenderer     | v1.0                     | coroutil-1.12.1-1.1.24.jar                       | None                                     |
	| UCH   | coroutil             | 1.12.1-1.1.24            | coroutil-1.12.1-1.1.24.jar                       | None                                     |
	| UCH   | configmod            | v1.0                     | coroutil-1.12.1-1.1.24.jar                       | None                                     |
	| UCH   | creativecore         | 1.9.9                    | CreativeCore_v1.9.19_mc1.12.2.jar                | None                                     |
	| UCH   | cyberware            | 0.2.10.12                | cyberware-1.12.2-0.2.10.12.jar                   | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCH   | ptrmodellib          | 1.0.0                    | Decocraft-2.5.5_1.12.2.jar                       | None                                     |
	| UCH   | props                | 2.5.5                    | Decocraft-2.5.5_1.12.2.jar                       | None                                     |
	| UCH   | thermalfoundation    | 2.3.10                   | ThermalFoundation-1.12.2-2.3.10.6-universal.jar  | None                                     |
	| UCH   | draconicevolution    | 2.3.10                   | Draconic-Evolution-1.12-2.3.10.284-universal.jar | None                                     |
	| UCH   | ic2                  | 2.8.67-ex112             | industrialcraft-2-2.8.67-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | galacticraftcore     | 4.0.1.169                | GalacticraftCore-1.12.2-4.0.1.169.jar            | None                                     |
	| UCH   | dsurround            | 3.4.9.11                 | DynamicSurroundings-1.12.2-3.4.9.11.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | presets              | 3.4.9.11                 | DynamicSurroundings-1.12.2-3.4.9.11.jar          | None                                     |
	| UCH   | dynamictrees         | 1.12.2-0.7.5c            | DynamicTrees-1.12.2-0.7.5c.jar                   | None                                     |
	| UCH   | dynamictreesbop      | beta 2                   | dynamictreesbop-beta+2.jar                       | None                                     |
	| UCH   | energyconverters     | 1.0.1.2                  | energyconverters_1.12.1-1.0.1.2.jar              | None                                     |
	| UCH   | exoticbirds          | 1.0                      | Exotic+Birds+1.12.2-1.4.0.jar                    | None                                     |
	| UCH   | extrabitmanipulation | 1.12-3.2.1               | ExtraBitManipulation-1.12-3.2.1.jar              | None                                     |
	| UCH   | galacticraftplanets  | 4.0.1.169                | Galacticraft-Planets-1.12.2-4.0.1.169.jar        | None                                     |
	| UCH   | mjrlegendslib        | 1.12.2-1.1.3             | MJRLegendsLib-1.12.2-1.1.3.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | extraplanets         | 1.12.2-0.3.2             | ExtraPlanets-1.12.2-0.3.2.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | fairylights          | 2.1.2                    | fairylights-2.1.2-1.12.x.jar                     | None                                     |
	| UCH   | fbp                  | 2.3.9                    | FancyBlockParticles-1.12.x-2.3.9.jar             | None                                     |
	| UCH   | jei                  | 4.8.5.158                | jei_1.12.2-4.8.5.158.jar                         | None                                     |
	| UCH   | mekanism             | 1.12.2-9.4.3.330         | Mekanism-1.12.2-9.4.3.330.zip                    | None                                     |
	| UCH   | sonarcore            | 5.0.6                    | sonarcore-1.12.2-5.0.6.jar                       | None                                     |
	| UCH   | fluxnetworks         | 3.0.5                    | fluxnetworks-1.12.2-3.0.5.jar                    | None                                     |
	| UCH   | foamfix              | 0.9.6-1.12.2             | foamfix-0.9.6-1.12.2-anarchy.jar                 | None                                     |
	| UCH   | forgelin             | 1.6.0                    | Forgelin-1.6.0.jar                               | None                                     |
	| UCH   | cfm                  | 4.2.0                    | furniture-4.2.0-1.12.2.jar                       | None                                     |
	| UCH   | ichunutil            | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                       | None                                     |
	| UCH   | gravitygun           | 7.0.0                    | GravityGun-1.12.2-7.0.1.jar                      | None                                     |
	| UCH   | cgm                  | 0.1.2                    | guns-0.1.2-1.12.2.jar                            | None                                     |
	| UCH   | llibrary             | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                        | None                                     |
	| UCH   | iceandfire           | 1.3.1                    | iceandfire-1.3.1-1.12.2.jar                      | None                                     |
	| UCH   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | jaff                 | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                    | None                                     |
	| UCH   | longfallboots        | 1.2.1a                   | longfallboots-1.2.1a.jar                         | None                                     |
	| UCH   | malisiscore          | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                     | None                                     |
	| UCH   | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| UCH   | mcef                 | 0.9                      | mcef-1.12.2-0.9.jar                              | None                                     |
	| UCH   | modelloader          | 1.0.5                    | modelloader-1.0.5.jar                            | None                                     |
	| UCH   | moreplanets          | 2.0.14                   | More-Planets-1.12.2-2.0.14-GC156.jar             | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCH   | moreplanetsextras    | 1.12.2-1.0               | MorePlanetsExtras-1.12.2-1.0.jar                 | None                                     |
	| UCH   | mysticalworld        | 0.1.1                    | mysticalworld-0.1.1.jar                          | None                                     |
	| UCH   | harvestcraft         | 1.12.2t                  | Pam's+HarvestCraft+1.12.2t.jar                   | None                                     |
	| UCH   | planetprogression    | 1.12.2-0.2.0             | PlanetProgression-1.12.2-0.2.0.jar               | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | playerrevive         | 1.0                      | PlayerRevive_v1.2.12_mc1.12.2.jar                | None                                     |
	| UCH   | portalgun            | 7.0.0                    | PortalGun-1.12.2-7.0.1.jar                       | None                                     |
	| UCH   | psf                  | 0.1.0-dev                | practical-space-fireworks-0.1.0.2-modjam.jar     | None                                     |
	| UCH   | projecte             | 1.12-PE1.0.0             | ProjectE-1.12-PE1.2.0.jar                        | None                                     |
	| UCH   | rewired              | 1.12.2                   | ReWIRED-1.0.3.jar                                | None                                     |
	| UCH   | signpic              | 2.8.1                    | SignPicture-1.12.1-2.8.1-universal.jar           | None                                     |
	| UCH   | soundfilters         | 0.10_for_1.12            | SoundFilters-0.10_for_1.12.jar                   | None                                     |
	| UCH   | spacex               | 1.0.0                    | spacex-1.12.2-1.0.0.jar                          | None                                     |
	| UCH   | texfix               | 4.0                      | TexFix+V-1.12-4.0.jar                            | None                                     |
	| UCH   | thebetweenlands      | 3.3.5                    | TheBetweenlands-3.3.5-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCH   | thermalexpansion     | 5.3.10                   | ThermalExpansion-1.12.2-5.3.10.15-universal.jar  | None                                     |
	| UCH   | toroquest            | 1.12.2-5.2               | toroquest-1.12.2-5.2.jar                         | None                                     |
	| UCH   | waddles              | 0.5.6                    | Waddles-1.12.2-0.5.6.jar                         | None                                     |
	| UCH   | wearablebackpacks    | 3.1.2                    | WearableBackpacks-1.12.2-3.1.2.jar               | None                                     |
	| UCH   | weather2             | 1.12.1-2.5.8             | weather2-1.12.1-2.5.8.jar                        | None                                     |
	| UCH   | webdisplays          | 1.0                      | webdisplays-1.12.2-1.0.jar                       | None                                     |
	| UCH   | elulib               | 0.1.12                   | elulib-0.1.12.jar                                | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.2.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SignPictureCorePlugin (SignPicture-1.12.1-2.8.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.5-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.6-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
CreativePatchingLoader (CreativeCore_v1.9.19_mc1.12.2.jar)
  
ForgelinPlugin (Forgelin-1.6.0.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
  org.blockartistry.DynSurround.asm.Transformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.169.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: vivecraft-1.12.2-jrbudda-6-final-r3-forge
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vivecraft,fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Sn0wSong_2_0_5 (incompatible), [1.11]_R3D.CRAFT_DR-64x_v0.5.18 Addon Final.zip (incompatible), [1.11.2] R3D CRAFT 64x (v0.3.1).zip, R3D CRAFT SHADER 64x (v0.1.8).zip (incompatible), [1.10] R3D CRAFT 64x PBRv2 (v0.3.0).zip (incompatible), [1.10] R3D CRAFT 64x POM (v0.3.0).zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by asiekierka** [comment]
Update Forge or downgrade FoamFix.

**Comment by jkroepke** [comment]
@asiekierka Whats the latest version that works with Forge RB?

**Comment by asiekierka** [comment]
0.9.5. I recommend using Latest Forge myself.

**Comment by jkroepke** [comment]
Thats fine while other mod authors recommend and build agist RB builds like AE2 it does. Its a problem but not your problem.
