### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Xiaminou** [asiekierka/FoamFix#135]
[crash-2018-04-07_13.52.26-client.txt](https://github.com/asiekierka/FoamFix/files/1886322/crash-2018-04-07_13.52.26-client.txt)

**Comment by asiekierka** [comment]
Please update Forge or downgrade FoamFix.

**Comment by Xiaminou** [comment]
Yeah I downgraded foamfix, can't update forge because of Botania's issue.
Shouldn't it tell you you need to update forge instead of this weird error?

**Comment by asiekierka** [comment]
Probably should. I'll fix that in an upcoming release, which will come sooner rather than later if I keep getting these reports :P
