### ISSUE TITLE
[1.12.2] Foamfix-0.9.6-anarchy makes the SilentGems Shields invisible.

### ISSUE THREAD

**Issue by SonicX8000** [asiekierka/FoamFix#137]
Minecraft: 1.12.2
Forge: 14.23.2.2654
Mode: Single-Player, but may also apply for Multi.

Mods:
foamfix-0.9.6-1.12.2-anarchy
SilentLib-1.12-2.2.17-98
SilentsGems-1.12-2.7.0-266

-----
Hope this is the right place... upon using 'foamfix-0.9.6-anarchy'... for some reason makes the shields from the Silent Gems mod invisible. You can still use them but... no 3D model displays, they're just completely invisible.

I downgraded to 'foamfix-0.9.5-1.12.2-anarchy' just to check something out and the shields render alright on that version.

I am unsure if the Lawful Version has the same issue. Config files from both mods are on their default settings when you first install them.

**Comment by asiekierka** [comment]
Lawful does not have the same issue, neither does 0.9.5.

Found the bug, will be fixed in 0.9.7.
