### ISSUE TITLE
I seem to be having a Village Generation Problem

### ISSUE THREAD

**Issue by 63502** [asiekierka/FoamFix#139]
The following crash occurred when my game tried to generate a desert village. from what little I understand, This crash seems to be some form of interaction between FoamFix and Totem Expansion. It only seems to occur when a desert village with sandstone buildings generates. I have generated plenty of normal villages and spruce villages with no issues with both mods installed. 

I don't know which mod is the actual cause, so I will link this issue on both mods issue pages.

[Crash Report](https://gist.github.com/63502/bca68b15089c731352399b2f5734efcb)

**Comment by 63502** [comment]
Fixed on Totem Expansion Side, Closing for now.

**Comment by asiekierka** [comment]
Yep, not our fault
