### ISSUE TITLE
Low FPS when I open Astral Sorcery's Tome

### ISSUE THREAD

**Issue by ghost** [asiekierka/FoamFix#142]
Hello
I'm having 1-2FPS when I open the tome of the mod Astral Sorcery
and the console is spamming this error : `[main/ERROR] [foamfix]: GL Error: Invalid value(1281) @ updateAnimation | fastPath mip=0
`

**Comment by asiekierka** [comment]
Hiatus until mid-August. For now, textures.fasterAnimation=0 in foamfix.cfg

**Comment by phyntos** [comment]
FastRender - OFF in Optifine
