### ISSUE TITLE
[1.12.2] Tinkers' cast bug

### ISSUE THREAD

**Issue by TheSnowyChickens** [asiekierka/FoamFix#144]
Hello,
the picture shows enough, I think.
It is a shovel cast, but it convert to a visual "blank cast" after 100% drying time.

![2018-05-06_13 06 24](https://user-images.githubusercontent.com/29357962/39672629-533668a4-512e-11e8-8e4b-3bea6552c4a0.png)

MC 1.12.2
1.12.2 - 14.23.3.2678
Mod list:
![grafik](https://user-images.githubusercontent.com/29357962/39672683-5b7832c6-512f-11e8-82c4-943e37e2df22.png)

It happend, after I put your mod into my test-pack, with all the other mods, no conflict occures.

**Comment by asiekierka** [comment]
Does it happen with just FoamFix and TConstruct?

**Comment by TheSnowyChickens** [comment]
No.

I think any of the other mods come into a conflict with your mod, but I dont know wich other mod apply this bug.
Thats why I post it here, maybe we can find the issue.

**Comment by TheSnowyChickens** [comment]
I found something on the TexFix Curse side : 

"FoamFix-Anarchy + Tinkers Construct: You will find to have some Tinkers Construct tools have just white, Textures. Sadly i can't fix that since its a multible things combined causes this issue.   
To fix that issue for you disable the dynamicItemModels option in FoamFix-Anarchy Config. This is only a issue with the Anarchy version. The law version is totally fine!"

That is not this issue from the picture, but also something I noticed. Maybe this 2 issues can stand in a context?

**Comment by asiekierka** [comment]
Maybe.

You shouldn't be using TexFix unless you have big textures (think Sphax-size), in my humble opinion. Not worth it. I'm also fairly confident disabling dynamicItemModels in FoamFix and keeping TexFix will give you higher RAM usage than removing TexFix and keeping dynamicItemModels enabled, _unless_ you have large textures - but that's also for you to test.

**Comment by TheSnowyChickens** [comment]
Okay, I play with the new default textures + a little 3D models resourcepack, so I will remove TexFix.

Thx master for this advice.^^

**Comment by ArmoredDrake1** [comment]
I just cant pour the liquid into a cast and the cast wont ever dry if I use a stone picaxe head to make a cast?
![image](https://user-images.githubusercontent.com/49134083/56488021-781c7300-6520-11e9-8847-d7666c56a326.png)
those are what I am using\
