### ISSUE TITLE
Possible conflict with chisel and bits

### ISSUE THREAD

**Issue by Sunconure11** [asiekierka/FoamFix#148]
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/393

**Comment by asiekierka** [comment]
I bet you'll get the same error on vanilla.

**Comment by Sunconure11** [comment]
This appears to be some weird issue with base metals and/or it's dependency.

https://github.com/MinecraftModDevelopmentMods/BaseMetals

**Comment by Sunconure11** [comment]
Issue cleared itself. Not sure what happened.
