### ISSUE TITLE
FoamFixCore references DummyModContainer

### ISSUE THREAD

**Issue by Aaron1011** [asiekierka/FoamFix#15]
The coremod class `FoamFixCore` extends `DummyModContainer`, which causes the latter class to be classloaded extremely early. [As detailed here](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482), this causes problems with SpongeForge, which needs to be able to transform `DummyModContainer` to function properly.

I'd be very grateful if you could split up the mod container from the coremod itself, in order to make your mod compatible with SpongeForge.

**Comment by asiekierka** [comment]
>transform DummyModContainer

Technical issues aside, I'm *very* curious as to what exactly you do to it.

**Comment by asiekierka** [comment]
This should fix the issue. However, I still am *very* curious as to what exactly you do to it.

**Comment by Aaron1011** [comment]
@asiekierka: [Sponge](https://www.spongepowered.org/) is a platform for making Minecraft plugins. One of our implementations is SpongeForge, which allows Sponge plugins to run on a Forge server, alongside mods.

Since we have an entire plugin API to implement, we end up needing to modify core Forge classes - in this case, to implement our [PluginContainer](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/plugin/PluginContainer.java) interface. Normally, we're able to register our transformer in time to modify the `ModContainer` interface - but when a coremod class extends `DummyModContainer`, the `ModContaner` interface ends up being classloaded before our code even has a chance to run.

Unfortuntately, the only solution to this kind of problem is to have the mod developer change their coremod class - unless we made people use a custom launcher, there's simply no way to make FML load our coremod earlier.

Feel free to join `#spongedev` on `irc.esper.net` if you have any other questions. Thanks for your help!

**Comment by asiekierka** [comment]
@Aaron1011 I was well aware of what Sponge is, I was just curious as to why you'd need to modify such a seemingly unrelated class. Thanks!

**Comment by Bubble0seven** [comment]
Is this issue fixed as i addressed in issue #1161 I was unable to load FTB Lite with the latest version of Lawful Edition for 1.10.2 and still not able to load

**Comment by asiekierka** [comment]
Lawful Edition does not trigger this bug, as it does not contain any classes related to the bug.
