### ISSUE TITLE
i broke a block whilst in creative mode

### ISSUE THREAD

**Issue by Apocolyptik** [asiekierka/FoamFix#150]
https://paste.dimdev.org/ijiquvufeb.mccrash
it was a copper ore block and i believe the ore block was from.. uhhh
either thermal foundation or base metals?
however, i don't know why the report is yelling about mystical agriculture, as i wasn't doing anything with that mod at the moment my game crashed
i was only holding a diamond pickaxe and i was using veinminer to clear a copper ore vein out of my way (i held shift and left clicked on the ore block)

**Comment by asiekierka** [comment]
Not a FoamFix issue. Not a Mystical Agriculture one either, necessarily; it could be that or VeinMiner, but I can't tell for sure.
