### ISSUE TITLE
help me please :D

### ISSUE THREAD

**Issue by MasterSloth1** [asiekierka/FoamFix#151]
changed a few setting in the config but now when ever i break astral sorcery blocks i insta crash to desktop.
Crash report
https://pastebin.com/nSjhnZ7M
Config File
https://pastebin.com/chfe1K7j

**Comment by asiekierka** [comment]
This is most likely a bug in Mystical Agriculture - see https://github.com/asiekierka/FoamFix/issues/150 .

The big question is: Does it happen without FoamFix?

**Comment by MasterSloth1** [comment]
even with foam fix disabled i still crash so sorry its not your fault.
new crash report
https://pastebin.com/1uS3eFRY
