### ISSUE TITLE
Crash after break Canola Crop 

### ISSUE THREAD

**Issue by Blatts12** [asiekierka/FoamFix#152]
Crash after break Canola Crop
https://pastebin.com/xjvtPrXS

**Comment by asiekierka** [comment]
Please test without FoamFix.

**Comment by Blatts12** [comment]
Okay, I think it's Vanilla Fix/JustEnoughIds's fault
https://paste.dimdev.org/usixerarid.mccrash

**Comment by asiekierka** [comment]
Yes, I'd bet on those two, esp. the latter.
