### ISSUE TITLE
"Using original slow path" message present when I'm using an AMD card

### ISSUE THREAD

**Issue by Broam** [asiekierka/FoamFix#153]
From my logs:
...
Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
Advanced Micro Devices, Inc. [AMD/ATI] Turks XT [Radeon HD 6670/7670]

Subsystem: XFX Pine Group Inc. Turks XT [Radeon HD 6670/7670]

Kernel driver in use: radeon
...
[20:50:57] [main/WARN] [foamfix]: Fast animated textures currently only seem to boost performance on AMD cards. Using original slow path.
...

I'm using the "radeon" driver on Linux. If your code is expecting AMD cards, your hardware detection is not seeing it on my system.

**Comment by asiekierka** [comment]
Thanks for the report! Could you send me the output of "glxinfo"?

**Comment by asiekierka** [comment]
As this is an older AMD card, could you also test if the "fast animated textures" patch even does anything?

1. Set mipmap levels to 0
2. Check/compare FPS numbers with foamfix.cfg -> textures.fasterAnimation=2, and textures.fasterAnimation=0

**Comment by Broam** [comment]
[glxinfo.txt](https://github.com/asiekierka/FoamFix/files/2130223/glxinfo.txt)

GLXInfo attached.
textures.FasterAnimation was 1 initially

There's not much difference.

**Comment by asiekierka** [comment]
Fixed in 0.10.0.
