### ISSUE TITLE
Crashes on out of memory

### ISSUE THREAD

**Issue by HaniXP** [asiekierka/FoamFix#156]
[foamfix]: GL Error: Out of memory(1285) @ uploadTextureMaxMips mip=0

i get this error constantly on my log.. and i keep crashing due to this,

what could be the reason? 

Answers r appreciated.

**Comment by asiekierka** [comment]
How much VRAM do you have? Are you using OptiFIne?

Try setting textures.enable=false in foamfix.cfg and let me know what happens.

**Comment by HaniXP** [comment]
Yes using the latest 1.12.2 optifine which is the E1 Ultra i guess,

we r basically playing on 1.12.2 modded server and we had  to use foamfix to increase our performance because keeping 1.7.10 mods started to lag us like hell in 1.12.2..

idk if optifine is also increasing the problem or increasing performance.. 

ok will change the texture to false in the config file, should i also do the same with the server's cfg? will inform u here if it fixed it.

**Comment by asiekierka** [comment]
The server does not care about the texture config change.

**Comment by HaniXP** [comment]
Yup, everything seems to work properly now, the thing was i had to upgrade my GPU & ram and thats it

**Comment by asiekierka** [comment]
*sighs*
