### ISSUE TITLE
Crash with rockhounding mod

### ISSUE THREAD

**Issue by wormzjl** [asiekierka/FoamFix#157]
Since it the crashlog mentioned foamfix in the first place:
https://gist.github.com/wormzjl/320cfb936ccc312450bbcbfe773ca0b2

Happens when someone broke a random block from that mod manually, only crashes the client not the server.
Does not crash if using some sort of block breaker to do the job
Edit: This only happens on a server.

**Comment by wormzjl** [comment]
related to https://github.com/asiekierka/FoamFix/issues/86 ?

**Comment by asiekierka** [comment]
Not a FoamFix bug.
