### ISSUE TITLE
[1.12.2] crash during change the language

### ISSUE THREAD

**Issue by TheSnowyChickens** [asiekierka/FoamFix#159]
MC: 1.12.2
FoamF: foamfix-0.9.9.1-1.12.2-anarchy
Forge: 1.12.2 - 14.23.4.2732

English (US) -> Shakespearean English (Kingdom of England) JFF :D
![grafik](https://user-images.githubusercontent.com/29357962/42594658-33e42292-8550-11e8-8542-757a073dabf1.png)
Yes, I have Optifine installed. :)

Crash report: https://paste.dimdev.org/vafutupatu.mccrash

**Comment by asiekierka** [comment]
Disable parallel baking. It's disabled by default for a reason.

**Comment by TheSnowyChickens** [comment]
Okay, thx.
