### ISSUE TITLE
Startup crash with 0.4.0 and 0.5b2 (Anarchy both)

### ISSUE THREAD

**Issue by gdude2002** [asiekierka/FoamFix#16]
Minecraft: 1.10.2
Forge: 2185 / 2202
Liteloader: 1.10-00-SNAPSHOT (Shouldn't be causing any issues though, haven't touched it)

---

Not really sure what's going on here, everything was fine until this morning.

Here's the crash log. https://gist.github.com/gdude2002/ef00b79150fa98928e65bad0399f42a4

---

I added a few mods to our pack:
* Reliquia
* Refined Relocation
* Natural Pledge
* Modular Routers

However, removing them one at a time hasn't fixed anything.

**Comment by asiekierka** [comment]
Noted. (As a workaround, you can use Lawful instead.)

**Comment by gdude2002** [comment]
Exact same problem with 0.5b2 Lawful

**Comment by gdude2002** [comment]
Likewise with 0.4.3 Lawful

**Comment by asiekierka** [comment]
>Exact same problem

Literally impossible - the crash is caused by "pl.asie.foamfix.coremod.BlockPosPatch.patchOtherClass", which *literally* does not exist in Lawful.

**Comment by gdude2002** [comment]
Hmm.. No, the exception raised is the same. Just now the error doesn't mention foamfix - it only mentions minecraft internals.

[crash-2017-01-04_16.00.49-client.txt](https://github.com/asiekierka/FoamFix/files/685352/crash-2017-01-04_16.00.49-client.txt)

**Comment by gdude2002** [comment]
OK, now it's not working without foamfix. It definitely did before, though - will do some more digging

**Comment by thommy101** [comment]
In the error is something with streams not found and if I remember correctly, the latest version of forge has an update with lambdas and therefore possibly streams. Maybe it's worth a shot to try the version before that (12.18.3.2185)?

**Comment by asiekierka** [comment]
Either way, it's not a FoamFix issue.
