### ISSUE TITLE
Noticing 2000ms lag spikes on server that mention foamfix

### ISSUE THREAD

**Issue by Entoarox** [asiekierka/FoamFix#160]
I run a server, and every so often there are heavy lag spikes of 2000ms or more ticks, according to reports made by Player's sampler mod, the majority of the cost is in calls to `net.minecraft.block.properties.PropertyEnum.hashCode_foamfix_old ()` taking a huge amount of time. (over 1200ms)

Now, as I am unaware how exactly foamfix works, I dont know if this is a issue in foamfix, or whatever black magic foamfix does not being used (with the `_old` suffix and all..)

So I would like to know if this is simply foamfix's optimisation just not being used (And if so, if there is anything I can do to make it get used...) or if it is actually something in foamfix that is having issues.

I have the sampler-created nps file available, if you need it.

**Comment by asiekierka** [comment]
_old is just vanilla's method wrapped. Could I have a look at the sampling?

**Comment by asiekierka** [comment]
Fixed in 0.10.0. Maybe.

**Comment by Entoarox** [comment]
http://cdn.kvdk.net/files/spike-2130-1924551449.nps

The sampler created file, and from what I managed to find while looking around myself, it is probably the https://github.com/asiekierka/FoamFix/blob/0.9.x-1.12.2/src/main/java/pl/asie/foamfix/coremod/injections/CachingHashCodeInject.java file that is relevant to this.

Hope you can somehow solve this with your awesome black magic, because the 2000ms lag spikes are extra annoying when new chunks get generated, as they seem to happen a lot more often then.

**Comment by asiekierka** [comment]
Try 0.10.0. It's not on CurseForge yet but you can find it on http://charset.asie.pl/

Note that this issue would also happen with vanilla; the goal in FoamFix was to fix it, but apparently I derped heavily when trying to

**Comment by Entoarox** [comment]
I was already under the presumption this was a vanilla related issue, I was just hoping you (As it apparently turns out) made a mistake fixing it, or (As I was honestly assuming) that I had a foamFix config option wrong. Thanks for your hard work in making MC less laggy!
