### ISSUE TITLE
"Anarchy" deduplicates less objects than "law"

### ISSUE THREAD

**Issue by AfterRebelion** [asiekierka/FoamFix#163]
Doesn't seem like a bug per se, but made a observation.
With **coremod enabled** seems to deduplicate many less objects than with **it disabled**. All tested with only Forge (14.23.4.2749) and FoamFix, but the same happened in a modpack. 

This will be a long post for something that probably isn't even a bug, so if you already know what causes this, you can close this without any problem, and sorry to waste your time.

Updated from 0.9.9.1 law to the new 0.10.0, and since it seemed like a big jump, recreated the config. Then testing a bit, observed in the log that the 0.10.0 version said it **deduplicated like 12 times less objects** than the previous version. After more testing, I came across that it wasn't related to the version changes to deduplication process, but from having enabled the coremod by default on the new 0.10.0 version.

So I tested different interactions of configs to see the results:

0.9.9.1 (law) with deduplicateModelsMaxRecursion=6 (default):
`[15:19:55] [main/INFO]: Deduplicated 199039 (+ 25550) objects.`

0.9.9.1 (anarchy) with deduplicateModelsMaxRecursion=6 (default):
`[15:37:42] [main/INFO]: Deduplicated 16386 (+ 22323) objects.`

0.10.0 with **coremod enabled** and deduplicateModelsMaxRecursion=9 (default):
`[15:25:29] [main/INFO]: Deduplicated 16498 (+ 22323) objects.`

0.10.0 with coremod enabled and deduplicateModelsMaxRecursion=6:
`[15:31:19] [main/INFO]: Deduplicated 16386 (+ 22323) objects.`

0.10.0 with **coremod disabled** and deduplicateModelsMaxRecursion=9:
`[15:46:44] [main/INFO]: Deduplicated 200637 (+ 25550) objects.`

**Comment by asiekierka** [comment]
FoamFix's coremod optimizations remove a lot of the objects which would have to be deduplicated otherwise. This works as intended.
