### ISSUE TITLE
Caught exception from ArmorPlus

### ISSUE THREAD

**Issue by CourtArtanis** [asiekierka/FoamFix#164]
I know it's an ArmorPlus exception, but it doesn't crash and the error doesn't appear in the log without foamfix.

The game crashes on forge loading screen with foamfix enabled.

Crash report:
https://gist.github.com/CourtArtanis/83bff7a0e34e91a69c4c1f1a600b25cf

**Comment by asiekierka** [comment]
:thinking: 

Could you try turning off model deduplication in the config?

**Comment by CourtArtanis** [comment]
Which entry is that, sir? 
B:deduplicateModelBakers=true 
or
B:deduplicate=true ?

**Comment by asiekierka** [comment]
Just turn off both.

**Comment by CourtArtanis** [comment]
That did the trick!

https://gist.github.com/CourtArtanis/532b3a49f34e695ee2250eba2b7493ad
The config as it is now for reference.

**Comment by asiekierka** [comment]
Ah, so it is a bug.

**Comment by sokratis12GR** [comment]
Eyy (At least the issue its not mine), but I'm curious to see what causes it.

**Comment by asiekierka** [comment]
Does the issue persist?

```
Mantle-1.12-1.3.2.24.jar
TConstruct-1.12.2-2.10.1.87.jar
armorplus-1.12.2-11.14.0.42.jar
thedragonlib-1.12.2-5.3.0.jar
```

plus FoamFix 0.10.2 and I could not reproduce it. Do I need additional mods?

**Comment by asiekierka** [comment]
Anyhow, could you try https://asie.pl/files/foamfix-0.10.3-test2-1.12.2-anarchy.jar ? I tried to blind-fix the issue.

**Comment by ThelianTech** [comment]
Asiekierka Im Currently having the same issue. im using: 
`
foamfix-0.10.2.1.12.2.jar/foamfix-0.10.0-1.12.2.jar (tried both versions separately)
Mantle-1.12-3.3.39.jar
TConstruct-1.12.2-2.11.0.106.jar
armorplus-1.12.2-11.13.0.40.jar
`
Currently getting the the same crash noted above. 
 I can Confirm that foamfix-0.10.3-test2-1.12.2-anarchy.jar did not crash with the armorplus and mantle same versions noted above. So the Blind Fix did work to resolve the issue.

**Comment by asiekierka** [comment]
Excellent, thanks!

**Comment by asiekierka** [comment]
0.10.3 released

**Comment by ThelianTech** [comment]
Your Welcome Will go download the update now, Thanks For the Quick Update.
