### ISSUE TITLE
Chrashing Menu

### ISSUE THREAD

**Issue by Rams59** [asiekierka/FoamFix#165]
Hey, I made my own custom modpack and it worked quite well. Than today i started it again and everytime i try to press singleplayer or any other  thing in the main menu it simplay chrashes and says foam fix issue. I tried some older Versions still chrashes. And it drives me crazy i didnt change anything on the pack and it worked fine yesterday.

Chrash Report : https://pastebin.com/idMaDkGP

**Comment by asiekierka** [comment]
java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;
	at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:125)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:40)
	at 

Update or remove NotEnoughItems
