### ISSUE TITLE
Crash-reports mentions FoamFix coremod, even when disabled.

### ISSUE THREAD

**Issue by AfterRebelion** [asiekierka/FoamFix#168]
Even when setting forceDisable=true in settings, crash-reports still mentions that you are using a coremod, and should use the lawful version.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 8/24/18 4:21 PM
Description: Manually triggered debug crash
```

**Comment by asiekierka** [comment]
Yes. I cannot disable that.

**Comment by AfterRebelion** [comment]
Well, in that case you can at least change the text, so it doesn't point to a no longer avaliable option.

**Comment by asiekierka** [comment]
That is fair.

**Comment by AfterRebelion** [comment]
`WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
Contact their authors BEFORE contacting forge`

Seems good enought now.
