### ISSUE TITLE
FoamFix Issue

### ISSUE THREAD

**Issue by GalacticGG** [asiekierka/FoamFix#170]
[crash-2017-07-10_21.44.37-client.txt](https://github.com/asiekierka/FoamFix/files/2321364/crash-2017-07-10_21.44.37-client.txt)

**Comment by asiekierka** [comment]
Outdated version of FoamFix, 1.5-month-old crash log, and most likely parallel model baking enabled in the config when it should be off by default.

:/

**Comment by GalacticGG** [comment]
i have change it in to foamfix 0.7.3 and set parallel model baking to false but it still not work

**Comment by asiekierka** [comment]
The latest is FoamFix 0.7.5, not 0.7.3.

**Comment by GalacticGG** [comment]
can you give me the link pls

**Comment by asiekierka** [comment]
All the official sources for FoamFix are up to date. Where did you get yours from?

https://asie.pl/files/mods/FoamFix/foamfix-0.7.5.jar

**Comment by GalacticGG** [comment]
internet :)
Thank for helping me out

**Comment by GalacticGG** [comment]
its still not work but i think it will never work because my computer is too weak
thank you anyway

**Comment by GalacticGG** [comment]
new issue
[crash-2018-08-28_16.13.19-client.txt](https://github.com/asiekierka/FoamFix/files/2327350/crash-2018-08-28_16.13.19-client.txt)
