### ISSUE TITLE
You know what, I don't know what happened here

### ISSUE THREAD

**Issue by Sunconure11** [asiekierka/FoamFix#172]
https://paste.dimdev.org/nikeduneni.mccrash

**Comment by asiekierka** [comment]
>at pl.asie.foamfix.coremod.injections.client.ModelLoaderParallelHelper

Probably something involving enabling unstable options, such as parallel model baking.

**Comment by Sunconure11** [comment]
I found the culprit

https://github.com/NightKosh/Gravestone-mod-Extended/issues/153
