### ISSUE TITLE
foamfix-0.10.1-1.12.2 Server Crash

### ISSUE THREAD

**Issue by HaniXP** [asiekierka/FoamFix#175]
Hi, ive been using Latest FoamFix Anarchy 1.12.2 Version for my server since months, 

but i had to try out the latest foamfix 0.10.1 version & it kept crashing my server all of a sudden

Also my server runs on SpongeForge.. could it be that the foamfix i imported to the server doesnt work for spongeforge except for anarchy?

Crashlog: https://gist.github.com/AgentHani/edc8e0d0dbc7010759efee1168c0bdbf

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/166
