### ISSUE TITLE
Crash on Startup - 1.10.2 Beta 2 Anarchy - Issue with foamfix and surge!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [asiekierka/FoamFix#18]
https://gist.github.com/P3rf3ctXZer0/17b1d750ec78d354b4b93ca1fb5c5b30

**Comment by P3rf3ctXZer0** [comment]
https://minecraft.curseforge.com/projects/surge?gameCategorySlug=mc-mods&projectID=250290

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Epoxide-Software/Surge/issues/10

**Comment by asiekierka** [comment]
Did you try with -Lawful? It's a good fallback version...
