### ISSUE TITLE
Optifine & Foamfix

### ISSUE THREAD

**Issue by Bigboom243** [asiekierka/FoamFix#181]
Minecraft version: 1.12.2
Forge version: 14.23.5.2795
Foamfix: 1.10.2 & 1.10.3
Optifine: HD U E2

Minecraft crashes whenever I attempt to run Optifine with foamfix 1.10.3 and 1.10.2.

Log for Foamfix 1.10.2:
[2018-12-04-7.log](https://github.com/asiekierka/FoamFix/files/2642190/2018-12-04-7.log)

Log for Foamfix 1.10.3:
[2018-12-04-6.log](https://github.com/asiekierka/FoamFix/files/2642191/2018-12-04-6.log)

**Comment by Bigboom243** [comment]
Ignore this! It wasn't a problem with foamfix but a problem with forge!

**Comment by asiekierka** [comment]
Incorrect! :astonished: 

That's a problem with OptiFine not being able to figure out how to patch the most recent version of Forge!
