### ISSUE TITLE
Client startup crash: out of bounds exception 

### ISSUE THREAD

**Issue by Mitchell5200** [asiekierka/FoamFix#186]
I've gone and added a new mod to my ATM3-remix install and the client fails to launch when i launch with it, the client will launch without foamfix but i like having ram spare. I have also reported this to the tardis mod team

Added mod https://minecraft.curseforge.com/projects/new-tardis-mod
Full log https://pastebin.com/7A6WSNGM

edit: foamfix version 0.10.2

**Comment by asiekierka** [comment]
Parallel model baking is disabled by default for a reason.
