### ISSUE TITLE
Optifne + foamfix = no sound

### ISSUE THREAD

**Issue by jredfox** [asiekierka/FoamFix#192]
OptiFine_1.12.2_HD_U_E3
foamfix-0.10.3-1.12.2

no sound on launch

**Comment by jredfox** [comment]
this issue has been open a month any closer to getting this fixed?

**Comment by asiekierka** [comment]
Not at all. As said on the CurseForge page, OptiFine is not officially supported - and I have no means to debug these issues, either.

**Comment by jredfox** [comment]
but, optimization mods should work together refusing to fix/debug it is like ignoring a valid issue regardless of who's side yours or optifine's. Even if it's on optifine's side at least you can open up an issue there.

**Comment by asiekierka** [comment]
I do not have time to spend forcing OptiFine to run in my development workspace. It is a big blob of proprietary code. Sorry.

**Comment by jredfox** [comment]
what if I told you only the latest version caused the no sound bug in foamfix-0.10.3-1.12.2. This bug didn't appear with FoamFix 0.10.2

**Comment by ate0ate** [comment]
I don't know if this may help you with your issue @jredfox but I am currently using Foamfix 0.10.3 along with OptiFine 1.12.2 HD U E4 pre1 and everything is working fine. It is available under the "preview versions" tab at the top of the Optifine downloads page. I did not try using the build of Optifine you are using specifically, so I cannot say if that also works for me. Still, the prerelease is newer and likely the last version for 1.12.2 we will see.

**Comment by jredfox** [comment]
the latest foamfix caused no sound to occur with OptiFine_1.12.2_HD_U_E3 and foamfix-0.10.3-1.12.2. Rolling back one version on foamfix fixes the bug so time to backport some code and figure out the bug then apply the fix for the next release

**Comment by Niko-sk2x** [comment]
Just in case you don't know I made running optifine in dev more or less trivial with this https://github.com/OpenCubicChunks/OptiFineDevTweaker. 
It does take a bit of fiddling around with enabling dumping class byte code in launchwrapper to debug optifine code but overall it's much easier than normally.

**Comment by ate0ate** [comment]
I get that @jredfox , but why roll back any changes to either mod when updating Optifine to the latest fixes things? Not trying to argue, just genuinely curious.

**Comment by jredfox** [comment]
Why would I debug two other mods that are not my own I don't work for foamfix/optifine just reporting the issue the side is probably foamfix since only the latest version causes the bug but, it could also be that optifine is replacing a class or method rather then pure edits. Updating to latest version @ate0ate is always recommended as more bugs are fixed sometimes created but, mostly fixed

the latest optifine version for foamfix to be used is OptiFine_1.12.2_HD_U_E3 and bug still persists

**Comment by ate0ate** [comment]
OptiFine 1.12.2 HD U E4 pre1 is the newest version of Optifine. Its just labeled as a prerelease. Look at the dates on the site itself. The version you are using is older. Either way, updating to the newest version of Optifine is unlikely to fix things for you as my testing of foamfix 0.10.3 using either Optifine U E3 or the newer U E4 both have functioning sound. This is using only both mods together and in a custom pack of 340 mods. Both work perfectly.

**Comment by Pythonic-Rainbow** [comment]
No , its not a FoamFix issue at all, I got this when I used to play with vanilla OptiFine.

**Comment by jredfox** [comment]
yeah close this issue it's on optifine's side
