### ISSUE TITLE
Crash whatever with Deduplicator

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [asiekierka/FoamFix#194]
[hs_err_pid7004.log](https://github.com/asiekierka/FoamFix/files/2933639/hs_err_pid7004.log)

**Comment by dannydjdk** [comment]
Several users of my pack (https://minecraft.curseforge.com/projects/real-tech) are having this crash as well. It is intermittent and seems to happen only when using the curse launcher with the native minecraft launcher. It doesn't seem to occur when using the jar launcher or Multi MC. According to the log, the crash occurs during model deduping.

Crash report: https://pastebin.com/B8gvDfu8
Log: https://pastebin.com/hZegb8cX

Using forge 14.23.5.2768
foamfix 0.10.3 (Haven't upgraded to 0.10.5 yet, but it doesn't appear this would have been addressed there.)

Let me know if there's anything we can do to help narrow this down. We have an issue for the pack open here: https://minecraft.curseforge.com/projects/real-tech/issues/19

**Comment by asiekierka** [comment]
The crash report link no longer works.

**Comment by dannydjdk** [comment]
Sorry, somehow I managed to add an E to the end of the link after pasting it. :/
https://pastebin.com/B8gvDfu8

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/258
