### ISSUE TITLE
Ticking entity crash, Foamfix 0.10.4

### ISSUE THREAD

**Issue by Justen-N** [asiekierka/FoamFix#197]
https://pastebin.com/2nRFCw0v

I'd guess that this field is added upon generation, so upgrading to this version may be world breaking. Just a guess though. Thanks, Asie.  (And, yes, there is a possibility that one of the other 113 mods is affecting this, but the call path doesn't hit anything else, and the most recent changes affect modspawning.)

**Comment by pauloelr** [comment]
Same for me and it was the only mod i updated on this time

**Comment by asiekierka** [comment]
Oh, no, that's totally my fault. And it's not world-breaking.

**Comment by Pythonic-Rainbow** [comment]
One thing to note, I am experiencing the same bug, but my server generated two reports.
One is the NoSuchField, and another is a "single tick took 60sec"

Problem also occurs on Client side when joining server

**Comment by Pythonic-Rainbow** [comment]
@asiekierka Is it related to https://github.com/asiekierka/FoamFix/blob/0.9.x-1.12.2/src/main/java/pl/asie/foamfix/coremod/injections/CachingMobSpawnerLogicInject.java#L49 ?

EDIT: From the latest commit https://github.com/asiekierka/FoamFix/commit/5f9da153a8363ce5bc17bdc8bc27d6bee54e644e obviously

Oh and yeah I saw you pulled 0.10.4 from CurseForge, guess you know it as well

**Comment by asiekierka** [comment]
Fixed in 0.10.5.
