### ISSUE TITLE
Crash when loading Enigmatica 2 Expert modpack

### ISSUE THREAD

**Issue by BrickVoid** [asiekierka/FoamFix#199]
https://paste.feed-the-beast.com/view/8acc91b8

The above crash happens while the Minecraft Launcher tries to build the modpack. This is before the Launcher successfully starts, a successful startup only happens if I relaunch this modpack. It appears to get partway through the Foamfix deduplication process then the launcher exits with this crash.

This suggests - to me, at least; I'm not a programmer so can't be sure - that on a cold startup of the modpack, there is an uninitialized variable that is initialized on the second startup.

**Comment by asiekierka** [comment]
Parallel baking is disabled by default for a reason. If it crashes, *disable it*, please.

**Comment by BrickVoid** [comment]
> 
> 
> Parallel baking is disabled by default for a reason. If it crashes, _disable it_, please.

I don't know why Niels enabled it in his modpack, but disabling it seems to have fixed the issue. Will report this fact back to him on his Discord about it.

Until such time as I get another crash, this issue could be considered resolved.
