### ISSUE TITLE
Casting exception with ender crystal?

### ISSUE THREAD

**Issue by darkhax** [asiekierka/FoamFix#2]
After adding the latest release to the MMD pack I get [this](https://gist.github.com/darkhax/7c2f278be1de0d293b239abc0a821bda) exception. The log doesn't give anything to suggest that it is your mod, however I can only reproduce it by adding your mod lol. For context, there is an ender crystal in my base.

**Comment by asiekierka** [comment]
Oh, I see. I messed up.

**Comment by asiekierka** [comment]
Fixed in 0.3.2.

**Comment by asiekierka** [comment]
Apparently it's not my fault after all! We got it reproduced without FoamFix.
