### ISSUE TITLE
Crash when using Galaxy Space

### ISSUE THREAD

**Issue by Romsik788** [asiekierka/FoamFix#200]
My minecraft crashes when using the Galaxy Space mod.
The developer says that this is not his problem.
[crash-2019-04-07_19.58.03-server.txt](https://github.com/asiekierka/FoamFix/files/3051835/crash-2019-04-07_19.58.03-server.txt)
[latest.log](https://github.com/asiekierka/FoamFix/files/3051836/latest.log)

**Comment by asiekierka** [comment]
That is true! It is not his problem.

Try disabling coremod.optimizedBlockPos

**Comment by Romsik788** [comment]
@asiekierka thank you. It's helped me.
