### ISSUE TITLE
[1.12.2] - Startup failure

### ISSUE THREAD

**Issue by RayzFoxx** [asiekierka/FoamFix#201]
Minecraft version: 1.12.2
foamFix version: 1.10.5

After updating GalaxySpace to version 2.0.7 in my modpack the game with foamFix can't startup, without foamFix game launches fine

log: https://pastebin.com/bbUCMHsR

**Comment by LitePenguins** [comment]
I have this exact error. Log: https://paste.dimdev.org/emesapiqod.mccrash

I recently updated GalaxySpace to 2.0.7 and AsmodeusCore to 0.0.7.

**Comment by LitePenguins** [comment]
Nevermind, fixed it through #200
