### ISSUE TITLE
[Crash on Startup] FoamFix with GregTech and GalaxySpace

### ISSUE THREAD

**Issue by ScienceDrummer** [asiekierka/FoamFix#204]
When starting the game up with these mods, I get this crash: https://paste.dimdev.org/orovakuxab.mccrash

Log: https://paste.dimdev.org/uralayimok.md

However when I disable a default setting in the config that "Optimizes BlockPos mutable/immutable getters to run on the same variables, letting them be inlined and thus theoretically increasing performance," to false. The game starts up fine.

I contacted the GregTech team first as that's what VanillaFix was telling me caused the problem and they said that it isn't a problem on their end.

**Comment by cyb3rm4n** [comment]
Same here: https://paste.dimdev.org/nalokenija.sql

**Comment by asiekierka** [comment]
Should be fixed in 0.10.6+.
