### ISSUE TITLE
Severe Issue with Schematics - 1.10.2 Foamfix Anarchy 5.0 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [asiekierka/FoamFix#21]
When foamfix is present I cannot use importing schematics command.

https://gist.github.com/P3rf3ctXZer0/81acc5333afdda68715e954af7bbf155

**Comment by asiekierka** [comment]
Does it work without FoamFix? It looks like a bug in Pam's HarvestCraft to me, honestly.

**Comment by asiekierka** [comment]
Okay, so what you're trying to do is load a BlockPamFruit with a metadata of 7, while BlockPamFruits can only legally exist for metadatas 0, 1 and 2. Your schematic may be corrupted.

**Comment by asiekierka** [comment]
@Ivorforce

Minecraft blocks have the tendency to crash on invalid metadata, please try...catch this:

    at ivorius.ivtoolkit.blocks.BlockStates.fromMetadata(BlockStates.java:38) ~[BlockStates.class:?]

**Comment by P3rf3ctXZer0** [comment]
I will let you know ; please don't close this yet!

**Comment by asiekierka** [comment]
I'm pretty sure I already know the reason, and even if it only manifests with FoamFix it is unlikely to be my fault - I read the code.

**Comment by P3rf3ctXZer0** [comment]
Understood. Thank you for your help.

**Comment by Ivorforce** [comment]
I've wrapped the call, it won't crash anymore (in the latest nightly / next release). Still though, custom as per vanilla is to just silently ignore invalid metadata and reset to a valid state :)

**Comment by asiekierka** [comment]
@Ivorforce Thanks for the note! That explains a few other issues.

**Comment by asiekierka** [comment]
@Ivorforce That's interesting, because BlockStateContainer.StateImplementation.withProperty says otherwise - and my code is trying to emulate that behaviour.

**Comment by asiekierka** [comment]
For future readers: as per https://github.com/CyclopsMC/IntegratedDynamics/issues/171, it is *not* customary to silently ignore invalid metadata in all cases in vanilla.
