### ISSUE TITLE
Crash after few minutes playing. After removal, works fine.

### ISSUE THREAD

**Issue by Davin13** [asiekierka/FoamFix#210]
Not super knowledgeable with reading logs or modpacks. Just know it stops crashing after few minutes of playtime without Foamfix. Thanks!

https://pastebin.com/gv4Gnren

**Comment by kreezxil** [comment]
the first few lines of your stack trace shows that librarianlib is your issue, I'd suggest reporting to them.

**Comment by Davin13** [comment]
Okay thanks
