### ISSUE TITLE
Java EXCEPTION_ACCESS_VIOLATION while loading E2 or E2E

### ISSUE THREAD

**Issue by CassandraRC7** [asiekierka/FoamFix#218]
Roughly half of the time, while loading this with Enigmatica 2 (Expert), Java crashes. The crash has not been duplicated without FoamFix, and can be duplicated by loading Enigmatica 2 Expert a few times. The attached log has been modified to replace my authentication token with [REDACTED], because having said token is a security risk.
[hs_err_pid6612.log](https://github.com/asiekierka/FoamFix/files/3273044/hs_err_pid6612.log)

**Comment by UnknownSilicon** [comment]
I'm also getting this issue in a custom pack

**Comment by Mrthomas20121** [comment]
That happen a lot for me in any of my packs. a fix would be to use your system java version assuming it's up to date.

**Comment by CassandraRC7** [comment]
Oh, I meant to add that there is a solution to this. Just uninstall FoamFix.

**Comment by asiekierka** [comment]
I have not managed to reproduce this, but then again - I cannot test with Mojang's specific build of Java, as I do not have a Windows setup to run such properly.

**Comment by Tschipp** [comment]
I know it has literally been a year but I'm gonna add my two cents: Had this happening with my custom pack too, some people say that setting `fboEnable:false` in the `options.txt` this issue can be avoided (not prevented completely though). Might just also be random chance.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/258

Specific to Mojang's build of Java; disabling model deduplication should work around it FOR NOW.
