### ISSUE TITLE
ConcurrentModificationException caused dedicated server to crash

### ISSUE THREAD

**Issue by kreezxil** [asiekierka/FoamFix#221]
## server crash report
https://pastebin.com/Hya8JfZq 

I don't know what the players were doing when it  happened and it appears to be one-off

**Comment by asiekierka** [comment]
Seems like it's caused by a mod modifying the entity removal list when it shouldn't. Possibly in a network packet.

**Comment by SirAron111** [comment]
https://pastebin.com/sbAy5KHB and https://pastebin.com/kLgduhCb seem to be the same issue. any hints on what could have caused this? my pack uses the newest version of the 1.12.2 foam fix as of this day FoamFix 0.10.8 (1.12.2) and apearantly setting :fixWorldEntityCleanup=true to false somehow fixes it but isnt that option important?
