### ISSUE TITLE
Severe performance issues for low end machine

### ISSUE THREAD

**Issue by CIosure** [asiekierka/FoamFix#222]
My friend has a really low-end single core A4-4020 APU, 8 GBs of DDR3-1333, and installing this mod makes it so he only gets like 1-4 FPS in game, without it he can reach 30+, is this a known issue?

**Comment by asiekierka** [comment]
"installing this mod"

I'm really curious, if it really doesn't happen *without* this mod. You might want to fiddle with the config flags in foamfix.cfg, disabling them one at a time until something holds.

**Comment by asiekierka** [comment]
This could be related to the sprite animation optimization not being liked by AMD drivers, which has been worked around by blocking the optimization on AMD cards.
