### ISSUE TITLE
Crashing on load with ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by jombo23** [asiekierka/FoamFix#223]
Howdy, I seem to be having issues with foamfix crashing minecraft on load. 
I'm loading the Allthemods3 modpack, and it crashes randomly citing issues with parallel model baking. 

I can only suspect that this is related to the number of threads my cpu has. This is a 22 core 44 thread xeon, and it just cant seem to keep it under control.

Crash log attached 🤔 
[crash-2019-07-22_17.09.59-client.txt](https://github.com/asiekierka/FoamFix/files/3419192/crash-2019-07-22_17.09.59-client.txt)

I'm more than happy to try things for you, just let me know.

Thanks~

**Comment by Monniasza** [comment]
It happened to me too.
[log.txt](https://github.com/asiekierka/FoamFix/files/3515121/log.txt)

**Comment by Monniasza** [comment]
Potential fix is avaliable [here](https://github.com/Monniasza/FoamFix/pull/1)

**Comment by asiekierka** [comment]
Don't use parallel model baking if your mods can't handle it. I'll just comment out the feature in 0.10.6...

**Comment by jombo23** [comment]
Felt the need to comment on this again. Still seems broken on high core counts. Causes an extra utilities model to get screwed up, and apparently a lot more, then some other stuff. Crash log attached. Runs with exactly the same modlist/etc on my friends 16 thread ryzen. Doesnt work on my 44 thread xeon... again. Apparently nothing to do with your parallel model baking not supporting some mods. Feel free to point out any of my mistakes.
using foamfix-0.10.10-1.12.2

Quite interested to see if its actually related to the number of threads or perhaps memory? I can think of anything different with my setup :\

This same thing happened a few months ago with my other friend and his 8700k. Would crash out for me, and would be fine for him.

Same as last time, I'm more than happy to do more testing/provide more logs, just let me know :)

[Crash log.txt](https://github.com/asiekierka/FoamFix/files/5623800/Crash.log.txt)

**Comment by asiekierka** [comment]
That's a different error altogether. You need to update your version of Forge.

**Comment by jombo23** [comment]
Yeah, I know that this is a bit out of date, but that doesnt really explain why it works fine for two other people with a 12 thread cpu and a 16 thread cpu, but not 44. For giggles I'll try updating forge though. Do you have a specific version you recommend?

Also I'm aware that its not the same issue, but from everything I can possibly see, this is related to my threadcount

**Comment by asiekierka** [comment]
The very latest version you can get. The margin of error isn't high - the refactor I rely on post 0.10.6? or so is only in very recent releases.

**Comment by jombo23** [comment]
Sigh. Well, I couldnt get newer forges to work on the pack im playing on now and cant be bothered to go through updating everything :P

That being said it does work on atm3r which is now forge 2854, which It did not the last time I had tried adding foamfix, but that must have been before some update.

Still strikes me as odd that this is only an issue for me while ive got two other people that can use it fine :\

Oh well, I was mostly interested in seeing if there was any performance difference between using foamfix and just giving it a 96 gig heap anyways. I suppose i can always try the older version and disable the parallel baking :)

Thanks!

**Comment by asiekierka** [comment]
Giving significantly more RAM than Minecraft needs can lead to putting more strain on the garbage collector, leading to *worse* performance. [Consider not doing that.](https://www.reddit.com/r/java/comments/21qwcp/jvm_performs_worse_if_too_much_memory_is_allocated/)

Also, yes, parallel baking remains unstable.

**Comment by jombo23** [comment]
graalvm loves to chew up memory and although dimension switching takes a little longer, it takes out all the little spikes when moving around. The only time ive found it to hurt was when i was only giving it 16 and it would build up and freak out and do a full GC and pause, however 32 and up seems more stable than 8-12 for heavy modpacks as it can just do small incremental gcs in its free time instead of waiting till it desperately needs more. Im sure a similar effect can be obtained with some proper gc tuning on the regular jvm, I just havent messed with it that far.

Anyways, 
Thanks
