### ISSUE TITLE
Crash Server/sponge 

### ISSUE THREAD

**Issue by diaverso** [asiekierka/FoamFix#224]
Good, I'm trying to make a server with a package of mods and plugins.
It is in version 1.12.2
The version for plugins I am using is "spongeforge-1.12.2-2838-7.1.7-RC3859"
All mods load perfectly, but when I put theirs I get an error.
Version of the mod "foamfix-0.10.5-1.12.2"

Link debug:
https://pastebin.com/rwGYTYCK

Link latest:
https://pastebin.com/mC9fwKpS

**Comment by rvveber** [comment]
I second this, same versions !
please fix! <3

**Comment by AlienXAXS** [comment]
I am also getting the same error - have removed FoamFix for now.

**Comment by rvveber** [comment]
To fix this you need to set the following options in the foamfix.cfg

optimizedBlockPos=false
patchChunkSerialization=false

**Comment by rvveber** [comment]
@AlienXAXS

**Comment by rvveber** [comment]
@diaverso

**Comment by AlienXAXS** [comment]
Thanks @RedCriterion -i knew about the patchChunkSerialization, but not the other :)

**Comment by asiekierka** [comment]
FoamFix 0.10.8 disables those automatically if SpongeForge is detected.
