### ISSUE TITLE
Sometimes Java crash probably by FoamFix

### ISSUE THREAD

**Issue by PanSzelescik** [asiekierka/FoamFix#229]
Not always, but crashes, i have three hs_err_pid:
[hs_err_pid7176.log](https://github.com/asiekierka/FoamFix/files/3501556/hs_err_pid7176.log)
[hs_err_pid11300.log](https://github.com/asiekierka/FoamFix/files/3501557/hs_err_pid11300.log)
[hs_err_pid11552.log](https://github.com/asiekierka/FoamFix/files/3501558/hs_err_pid11552.log)

And replay_pid:
[replay_pid7176.log](https://github.com/asiekierka/FoamFix/files/3501560/replay_pid7176.log)
[replay_pid11300.log](https://github.com/asiekierka/FoamFix/files/3501561/replay_pid11300.log)
[replay_pid11552.log](https://github.com/asiekierka/FoamFix/files/3501562/replay_pid11552.log)

Forge: 1.12.2 - 14.23.5.2838
FoamFix: 0.10.5
Java: 1.8.0_51 (because Mojang Launcher installs own Java)
120 files in mods folder

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/258
