### ISSUE TITLE
World Load Crash w/ Dynamic Surroundings

### ISSUE THREAD

**Issue by MafooHamhead** [asiekierka/FoamFix#23]
Loading a new or existing world with this setup causes a crash:

**Minecraft** Version: 1.10.2
**Forge** Version: 2202
**Foamfix** Version: 0.5.0 Anarchy
**Dynamic Surroundings** Version: 3.2.1.0

**Crash Log:** https://hastebin.com/tasobufiho.pas

Worked with previous version of the mod (3.2.0.0), so not sure if it is on your end or theirs.

They're not sure what they can do on their end.

**DS' Github:** https://github.com/OreCruncher/DynamicSurroundings/issues/24

**Comment by OreCruncher** [comment]
[I do have a class](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/mod/DynSurround/util/MyMutableBlockPos.java) that derives from BlockPos.MutableBlockPos and I suspect that is where the problem lies.

**Comment by asiekierka** [comment]
Yes, for some reason my coremod is not catching that.

Disable "optimizedBlockPos" in "coremod" as a workaround for the time being.

**Comment by asiekierka** [comment]
@OreCruncher Overriding non-mutable BlockPos methods in this way is not a good idea for performance; if you do so, the JIT may have difficulties inlining the methods (which is a good thing to have for methods called thousands of times) - in fact, this is what "optimizedBlockPos" does for the getters. It's a small thing, but still worth considering.

Anyhow, @OreCruncher , @MafooHamhead Could you please try http://asie.pl/foamfix-0.5.1-test1-anarchy.jar ?

**Comment by OreCruncher** [comment]
@asiekierka Sure.  The reason I did this is because BlockPos.MutableBlockPos is only partially mutable. :\  I have scanning routines that process 1Ks of blocks per tick and I would have been creating new BlockPos objects very frequently.  MutableBlockPos should be fixed up and made final...

**Comment by asiekierka** [comment]
@OreCruncher MutableBlockPos has a mutable set method. The only thing I'm recommending you to do is to *not* use @Override on the mutable variants of methods. First of all, that stops the JIT from doing inlining optimizations; second, that might break mods which expect said methods to be immutable.

**Comment by asiekierka** [comment]
@OreCruncher Also, you might want to consider caching surroundings data and listening to block neighbor changes using something like an IWorldEventListener to greatly improve performance.

**Comment by OreCruncher** [comment]
@asiekierka The setPos() - that is the change I was looking at.  Testing a version of the mod that eliminates my class entirely.  As for the caching, is there something specific you have seen?

**Comment by asiekierka** [comment]
@OreCruncher No, I just remember how we had it implemented over at BuildCraft, where robots had to be able to quickly query massive areas of the world. Most of the comparisons/checks were cached and updated when necessary.

**Comment by OreCruncher** [comment]
Gottcha.  One of the scanners is a cuboid scanner, and it will only scan the new blocks that enter into range as the player moves, or if there is a notify that comes in and that block is within the cuboid.  The other scanner randomly selects blocks over an area around the player, and it uses cached values from the previous block check if possible.  I do plan on putting FoamFix in my test environment later today because I am curious as to how it would further improve things.

**Comment by asiekierka** [comment]
@OreCruncher What I'm wondering, however, is: does the build I linked fix the crash?

**Comment by OreCruncher** [comment]
@asiekierka NVW - found a link to a test JAR above.  It passes the sniff test and it appears to be working.

**Comment by asiekierka** [comment]
Thank you.
