### ISSUE TITLE
Foamfix / UCW crash

### ISSUE THREAD

**Issue by MxtressMyxx** [asiekierka/FoamFix#230]
See glut of logs here:

https://openeye.openmods.info/crashes/1cde15cef2fb88ace065c63d868f03f7

There are many more like this. Sometimes client will load, sometimes it wont.

**Comment by CritFlaw** [comment]
https://pastebin.com/0S5qQT3P Ditto

**Comment by asiekierka** [comment]
Being tackled in https://github.com/asiekierka/FoamFix/issues/239
