### ISSUE TITLE
Out of Bounds error, dedicated server in FoamFix 0.10.5 (1.12.2)  Download

### ISSUE THREAD

**Issue by kreezxil** [asiekierka/FoamFix#231]
http://paste.ubuntu.com/p/ycs58B9HKn/

I have no idea what caused it nor how to reproduce it

**Comment by asiekierka** [comment]
Did you enable a config option which is disabled by default (for a reason)?

**Comment by kreezxil** [comment]
Nope, using the stock config. here is my config currently http://paste.ubuntu.com/p/Kp279yBSTP/

**Comment by asiekierka** [comment]
Something terrible happened to your JVM and I've no clue if it's FoamFix-specific or not. Try disabling fasterEntityLookup.

**Comment by kreezxil** [comment]
Thanks for the 2 months later response. I have moved on from this on the day I reported I don't remember what the solution was. Seems I chose to remove Foamfix from the World of Dragons mod pack. We'll just close this.
