### ISSUE TITLE
Foamfix forge release - forge is now stable in 1.14.4

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [asiekierka/FoamFix#235]
![2019-09-12 19_46_01-Minecraft Forge](https://user-images.githubusercontent.com/10351221/64830429-00fe7e80-d596-11e9-94ec-e31287378725.jpg)

You once told me updates would take place when forge released a stable version well - its finally here 👯

**Comment by asiekierka** [comment]
That was a very long time ago; at this time, I do not plan on bringing any of my mods past 1.12.2, or maintaining any existing post-1.12.2 releases further. Sorry.
