### ISSUE TITLE
Foamfix x unlimited chisel crashing on load

### ISSUE THREAD

**Issue by ValentineBlaze** [asiekierka/FoamFix#238]
creating a mod pack and have ran it without foamfix no problem (except a whole lot more ram usage) but when I try running it with I get this https://paste.dimdev.org/uyepejomiv.mccrash I may be missing a setting somewhere in configs, wondering if you may know what I can do to fix

**Comment by ValentineBlaze** [comment]
okay seems to be related to #230 and #234 which means since its different mods being effected means it may not be foamfix itself but a third hidden mod effecting things, now to hunt for what mod that may be, if anyone has any ideas would be a great help. okay currently solved my problem by getting rid of the blood arsenal mod but idk why that would effect it but it did and it also didn't work, cause I still got the same crash running again.. seems to happen sometimes but not always

**Comment by asiekierka** [comment]
Uses NotEnoughIDs, which is no longer maintained; also, duplicate; workaround will be added soon.
