### ISSUE TITLE
[FoamFix 1.14.4]FoamFix doesn't seem to play well with Towelette

### ISSUE THREAD

**Issue by Neubulae** [asiekierka/FoamFix#240]
https://pastebin.com/uDb115wu
This is the part it generated when the game crashes. No other crash reports are generated.

**Comment by ChloeDawn** [comment]
Does this only occur with FoamFix installed or can it be reproduced without?

**Comment by asiekierka** [comment]
FYI: FoamFix for 1.14 is not currently maintained

**Comment by Neubulae** [comment]
> Does this only occur with FoamFix installed or can it be reproduced without?

Confirmed former.

**Comment by Virtuoel** [comment]
This has been fixed on Towelette's side.

**Comment by Neubulae** [comment]
Since Towellete already resolved this issue months ago, here I am to close the issue.
