### ISSUE TITLE
Placing a cobblestone while Shift + right clicking on top of a hopper instantly crashes the server

### ISSUE THREAD

**Issue by stumbleverse** [asiekierka/FoamFix#242]
I am playing in all the magic 1.6.

Tested twice, worked every time.

Crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  wings (wings-1.1.5-1.12.2.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  AALoadingPlugin (arcanearchives-0.2.0.1.jar)
  Incorporeal Tweaker (incorporeal-1.1.4.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  Quark Plugin (Quark-r1.6-174.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.10-core.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.156.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  Wizardry Plugin (wizardry-0.10.8.jar)
  Botania Tweaks Core (botaniatweaks-1.8.6.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 10/24/19 10:48 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.tileentity.TileEntityHopper.func_174917_b(TileEntityHopper.java:275)
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:309)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:142)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.tileentity.TileEntityHopper.func_174917_b(TileEntityHopper.java:275)
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:309)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:142)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // pl.asie.foamfix.common.TileEntityFasterHopper
	Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper // minecraft:hopper)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (57,9,125), Chunk: (at 9,0,13 in 3,7; contains blocks 48,0,112 to 63,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper // minecraft:hopper)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -9114348421172245801
	Level generator: ID 07 - quark_realistic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (224,64,248), Chunk: (at 0,4,8 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2713694 game time, 2832520 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 3796 (now: true), thunder time: 134191 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 910195488 bytes (868 MB) / 2138701824 bytes (2039 MB) up to 5234491392 bytes (4992 MB)
	JVM Flags: 15 total; -Xmx5G -Xms2G -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3
	IntCache: cache: 0, tcache: 3, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 171 mods loaded, 170 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version                  | Source                                                   | Signature                                |
	|:------ |:------------------------- |:------------------------ |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2                   | minecraft.jar                                            | None                                     |
	| LCHIJA | mcp                       | 9.42                     | minecraft.jar                                            | None                                     |
	| LCHIJA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                     | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | incorporeal_core          | 1.1.0                    | minecraft.jar                                            | None                                     |
	| LCHIJA | foamfixcore               | 7.7.4                    | minecraft.jar                                            | None                                     |
	| LCHIJA | botania_tweaks_core       | -100                     | minecraft.jar                                            | None                                     |
	| LCHIJA | appliedenergistics2       | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar                     | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJA | mantle                    | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                                 | None                                     |
	| LCHIJA | mysticalmechanics         | 0.10                     | Mystical Mechanics-0.10.jar                              | None                                     |
	| LCHIJA | embers                    | 1.13-hotfix2             | EmbersRekindled-1.13-hotfix2.jar                         | None                                     |
	| LCHIJA | aetherworks               | 1.12.2-1.0.0.3           | AetherWorks-1.12.2-1.0.0.3.jar                           | None                                     |
	| LCHIJA | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | avaritia                  | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar                   | None                                     |
	| LCHIJA | placebo                   | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                                 | None                                     |
	| LCHIJA | singularities             | 2.4.1                    | Singularities-1.12.2-2.4.1.jar                           | None                                     |
	| LCHIJA | crafttweaker              | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                            | None                                     |
	| LCHIJA | mtlib                     | 3.0.6                    | MTLib-3.0.6.jar                                          | None                                     |
	| LCHIJA | modtweaker                | 4.0.17                   | modtweaker-4.0.17.jar                                    | None                                     |
	| LCHIJA | jei                       | 4.15.0.287               | jei_1.12.2-4.15.0.287.jar                                | None                                     |
	| LCHIJA | projecte                  | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                              | None                                     |
	| LCHIJA | chisel                    | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                             | None                                     |
	| LCHIJA | thaumcraft                | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                         | None                                     |
	| LCHIJA | twilightforest            | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar              | None                                     |
	| LCHIJA | tconstruct                | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                         | None                                     |
	| LCHIJA | p455w0rdslib              | 2.2.156                  | p455w0rdslib-1.12.2-2.2.156.jar                          | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | ae2wtlib                  | 1.0.30                   | AE2WTLib-1.12.2-1.0.30.jar                               | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | akashictome               | 1.2-12                   | AkashicTome-1.2-12.jar                                   | None                                     |
	| LCHIJA | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                               | None                                     |
	| LCHIJA | gbook_snapshot            | 2.9.1.s5                 | Guidebook-1.12.2-2.9.1.s5.jar                            | None                                     |
	| LCHIJA | arcanearchives            | 0.2.0.1                  | arcanearchives-0.2.0.1.jar                               | None                                     |
	| LCHIJA | astralsorcery             | 1.10.19                  | astralsorcery-1.12.2-1.10.19.jar                         | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | attributefix              | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | quark                     | r1.6-174                 | Quark-r1.6-174.jar                                       | None                                     |
	| LCHIJA | autoreglib                | 1.3-32                   | AutoRegLib-1.3-32.jar                                    | None                                     |
	| LCHIJA | botania_tweaks            | 1.8.6                    | botaniatweaks-1.8.6.jar                                  | None                                     |
	| LCHIJA | botania                   | r1.10-361                | Botania r1.10-361.jar                                    | None                                     |
	| LCHIJA | avaritiatweaks            | 1.12.2-1.1               | AvaritiaTweaks-1.12.2-1.1.jar                            | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | badwithernocookiereloaded | 1.12.2-3.3.16            | badwithernocookiereloaded-1.12.2-3.3.16.jar              | None                                     |
	| LCHIJA | base                      | 3.13.0                   | base-1.12.2-3.13.0.jar                                   | None                                     |
	| LCHIJA | bhc                       | 2.0.3                    | baubley-heart-canisters-1.12.2-2.0.3.jar                 | None                                     |
	| LCHIJA | betterbedrockgen          | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar                    | None                                     |
	| LCHIJA | betterbuilderswands       | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar        | None                                     |
	| LCHIJA | patchouli                 | 1.0-20                   | Patchouli-1.0-20.jar                                     | None                                     |
	| LCHIJA | bewitchment               | 0.20.6                   | bewitchment-1.12.2-0.0.20.6.jar                          | None                                     |
	| LCHIJA | birdsfoods                | 3.1 - [1.12]             | birdsfoods-1.12 - 3.1.jar                                | None                                     |
	| LCHIJA | blockcraftery             | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                           | None                                     |
	| LCHIJA | guideapi                  | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                              | None                                     |
	| LCHIJA | bloodmagic                | 1.12.2-2.4.1-103         | BloodMagic-1.12.2-2.4.1-103.jar                          | None                                     |
	| LCHIJA | bloodarsenal              | 1.12.2-2.2.0-28          | BloodArsenal-1.12.2-2.2.0-28.jar                         | None                                     |
	| LCHIJA | bookshelf                 | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | nibbler                   | 0.4.1                    | nibbler-1.12.2-0.4.1.jar                                 | None                                     |
	| LCHIJA | botaunomy                 | 0.2.1                    | botaunomy-1.12.2-0.2.1.jar                               | None                                     |
	| LCHIJA | buildinggadgets           | 2.7.1                    | BuildingGadgets-2.7.1.jar                                | None                                     |
	| LCHIJA | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                                 | None                                     |
	| LCHIJA | chesttransporter          | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                        | None                                     |
	| LCHIJA | chiselsandbits            | 14.33                    | chiselsandbits-14.33.jar                                 | None                                     |
	| LCHIJA | clumps                    | 3.1.2                    | Clumps-3.1.2.jar                                         | None                                     |
	| LCHIJA | cyclopscore               | 1.5.0                    | CyclopsCore-1.12.2-1.5.0.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | commoncapabilities        | 2.4.4                    | CommonCapabilities-1.12.2-2.4.4.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | contenttweaker            | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                          | None                                     |
	| LCHIJA | conarm                    | 1.2.4                    | conarm-1.12.2-1.2.4.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | craftingtweaks            | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                          | None                                     |
	| LCHIJA | craftstudioapi            | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar       | None                                     |
	| LCHIJA | crafttweakerjei           | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                            | None                                     |
	| LCHIJA | cucumber                  | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                                | None                                     |
	| LCHIJA | darkutils                 | 1.8.226                  | DarkUtils-1.12.2-1.8.226.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | dragonmounts              | 1.12.2-1.6.3             | DragonMounts2-1.12.2-1.6.3.jar                           | None                                     |
	| LCHIJA | eerieentities             | 1.0.7                    | EerieEntities-1.12.2-1.0.7.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ebwizardry                | 4.1.4                    | Electroblob's Wizardry - 4.1.4 - MC 1.12.2.jar           | None                                     |
	| LCHIJA | emberroot                 | 1.3.9                    | EmberRootZoo-1.12.2-1.3.10.jar                           | None                                     |
	| LCHIJA | embersified               | 1.0.3                    | Embersified-1.12.2-1.0.3.jar                             | None                                     |
	| LCHIJA | emberstic                 | 0.1.0                    | emberstic-0.1.0.jar                                      | None                                     |
	| LCHIJA | eplus                     | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage              | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | equivalentenergistics     | 0.8.3                    | EquivalentEnergistics-1.12.2-PE_1.3.1B-AE2_RV6-0.8.3.jar | None                                     |
	| LCHIJA | evilcraft                 | 0.10.77                  | EvilCraft-1.12.2-0.10.77.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | evilcraftcompat           | 1.0.0                    | EvilCraft-1.12.2-0.10.77.jar                             | None                                     |
	| LCHIJA | hammercore                | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | expequiv                  | 12r                      | ExpandedEquivalence-1.12.2-12r.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | theoneprobe               | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                              | None                                     |
	| LCHIJA | extrabotany               | 55                       | ExtraBotany-r1.1-55-fixed.jar                            | None                                     |
	| LCHIJA | fastfurnace               | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                             | None                                     |
	| LCHIJA | fastleafdecay             | v14                      | FastLeafDecay-v14.jar                                    | None                                     |
	| LCHIJA | fastbench                 | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                           | None                                     |
	| LCHIJA | fencejumper               | 1.0.5                    | fencejumper-1.12-1.0.5.jar                               | None                                     |
	| LCHIJA | foamfix                   | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                                | None                                     |
	| LCHIJA | forgelin                  | 1.8.3                    | Forgelin-1.8.3.jar                                       | None                                     |
	| LCHIJA | ftblib                    | 5.4.3.130                | FTBLib-5.4.3.130.jar                                     | None                                     |
	| LCHIJA | ftbutilities              | 5.4.0.100                | FTBUtilities-5.4.0.100.jar                               | None                                     |
	| LCHIJA | itemfilters               | 1.0.3.12                 | ItemFilters-1.0.3.12.jar                                 | None                                     |
	| LCHIJA | ftbquests                 | 1.7.2.189                | FTBQuests-1.7.2.189.jar                                  | None                                     |
	| LCHIJA | ftbbackups                | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.5.jar                          | None                                     |
	| LCHIJA | limelib                   | 1.7.12                   | limelib-1.12.2-1.7.12.jar                                | None                                     |
	| LCHIJA | furnus                    | 2.1.8                    | furnus-1.12.2-2.1.8.jar                                  | None                                     |
	| LCHIJA | harvest                   | 1.12-1.2.7-20            | Harvest-1.12-1.2.7-20.jar                                | None                                     |
	| LCHIJA | incorporeal               | 1.1.4                    | incorporeal-1.1.4.jar                                    | None                                     |
	| LCHIJA | initialinventory          | 2.0.2                    | InitialInventory-3.0.0.jar                               | None                                     |
	| LCHIJA | integrateddynamics        | 1.0.18                   | IntegratedDynamics-1.12.2-1.0.18.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | integrateddynamicscompat  | 1.0.0                    | IntegratedDynamics-1.12.2-1.0.18.jar                     | None                                     |
	| LCHIJA | integratedtunnels         | 1.6.10                   | IntegratedTunnels-1.12.2-1.6.10.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | integratedtunnelscompat   | 1.0.0                    | IntegratedTunnels-1.12.2-1.6.10.jar                      | None                                     |
	| LCHIJA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jee                       | 1.0.7                    | JustEnoughEnergistics-1.12.2-1.0.7.jar                   | None                                     |
	| LCHIJA | kjlib                     | 1.0.4                    | kjlib-1.0.4.jar                                          | None                                     |
	| LCHIJA | shotgunsandglitter        | 1.6                      | shotgunsandglitter-1.6.jar                               | None                                     |
	| LCHIJA | librarianlib              | 4.19.2                   | librarianlib-1.12.2-4.19.2-release.jar                   | None                                     |
	| LCHIJA | psi                       | r1.1-77                  | Psi-r1.1-77.jar                                          | None                                     |
	| LCHIJA | magipsi                   | 1.3                      | MagicalPsi-1.3.2.jar                                     | None                                     |
	| LCHIJA | mysticalagriculture       | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar                     | None                                     |
	| LCHIJA | matc                      | 1.0.1-hotfix             | matc-1.0.1-hotfix.jar                                    | None                                     |
	| LCHIJA | mcjtylib_ng               | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                                  | None                                     |
	| LCHIJA | tbone                     | v1.6.8+mc1.12.2          | TBone-v1.6.8+mc1.12.2.jar                                | None                                     |
	| LCHIJA | metalchests               | v6.1.0+mc1.12.2          | MetalChests-v6.1.0+mc1.12.2.jar                          | None                                     |
	| LCHIJA | minicoal                  | 1.0                      | minicoal-1.12.2-1.0.jar                                  | None                                     |
	| LCHIJA | mist                      | alpha_c_09               | MistWorld_1.12.2_alpha_c_09.jar                          | None                                     |
	| LCHIJA | testdummy                 | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                               | None                                     |
	| LCHIJA | morpheus                  | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                              | None                                     |
	| LCHIJA | llibrary                  | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs               | 1.5.4                    | mowziesmobs-1.5.4.jar                                    | None                                     |
	| LCHIJA | multimob                  | 1.0.5                    | multimob-1.0.5.jar                                       | None                                     |
	| LCHIJA | mystcraft                 | 0.13.7.04                | mystcraft-1.12.2-0.13.7.04.jar                           | None                                     |
	| LCHIJA | mysticalagradditions      | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar                    | None                                     |
	| LCHIJA | mysticalwildlife          | 1.3.0                    | mysticalwildlife-1.12.2-1.3.0.jar                        | None                                     |
	| LCHIJA | mysticalworld             | 1.12.2-1.3.2             | MysticWorld-1.12.2-1.3.2.jar                             | None                                     |
	| LCHIJA | naturalpledge             | 3.0.3                    | NaturalPledge-r3.1.2.jar                                 | None                                     |
	| LCHIJA | naturesaura               | r17                      | NaturesAura-r17.jar                                      | None                                     |
	| LCHIJA | naturescompass            | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                          | None                                     |
	| LCHIJA | netherchest               | 1.1.1                    | netherchest-1.1.1.jar                                    | None                                     |
	| LCHIJA | oreexcavation             | 1.4.140                  | OreExcavation-1.4.140.jar                                | None                                     |
	| LCHIJA | oeintegration             | 2.3.4                    | oeintegration-2.3.4.jar                                  | None                                     |
	| LCHIJA | soot                      | 1.6                      | Soot-1.6.jar                                             | None                                     |
	| LCHIJA | thebetweenlands           | 3.4.10                   | TheBetweenlands-3.4.10-universal.jar                     | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | pewter                    | 1.4.3                    | Pewter-1.4.3.jar                                         | None                                     |
	| LCHIJA | primitivemobs             | 1.2.3a                   | primitivemobs-1.2.3a.jar                                 | None                                     |
	| LCHIJA | quarkoddities             | 1                        | QuarkOddities-1.12.2.jar                                 | None                                     |
	| LCHIJA | rangedpumps               | 0.5                      | rangedpumps-0.5.jar                                      | None                                     |
	| LCHIJA | refinedstorage            | 1.6.15                   | refinedstorage-1.6.15.jar                                | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | refinedexchange           | 2.1.1                    | refinedexchange-2.1.1.jar                                | None                                     |
	| LCHIJA | refinedstorageaddons      | 0.4.4                    | refinedstorageaddons-0.4.4.jar                           | None                                     |
	| LCHIJA | refinedstoragerequestify  | ${version}               | refinedstoragerequestify-1.12.2-1.0.2-3.jar              | None                                     |
	| LCHIJA | xreliquary                | 1.12.2-1.3.4.786         | Reliquary-1.12.2-1.3.4.786.jar                           | None                                     |
	| LCHIJA | rockcandy                 | 1.12.2-3.00              | rockcandy-1.12.2-3.0.0.jar                               | None                                     |
	| LCHIJA | rootsclassic              | 1.12.2-1.1.5             | RootsClassic-1.12.2-1.1.5.jar                            | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCHIJA | rustic                    | 1.1.1                    | rustic-1.1.1.jar                                         | None                                     |
	| LCHIJA | rusticthaumaturgy         | 4.4a                     | Rustic Thaumaturgy-4.4a.jar                              | None                                     |
	| LCHIJA | soulshardsrespawn         | 1.12.2-1.1.1-13          | SoulShardsRespawn-1.12.2-1.1.1-13.jar                    | None                                     |
	| LCHIJA | sct                       | 1.0.3                    | StoneCraftingTable-1.12.2-1.0.3.jar                      | None                                     |
	| LCHIJA | storagedrawers            | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                          | None                                     |
	| LCHIJA | tammodized                | 0.15.6                   | TamModized-1.12.2-0.15.6.jar                             | None                                     |
	| LCHIJA | thaumicenergistics        | 2.2.3                    | thaumicenergistics-2.2.3.jar                             | None                                     |
	| LCHIJA | thaumicequivalence        | 1.12.2-1.0.5             | ThaumicEquivalence-1.12.2-1.0.5.jar                      | None                                     |
	| LCHIJA | thaumicgrid               | 1.0.12                   | ThaumicGrid-1.0.12.jar                                   | None                                     |
	| LCHIJA | tcinventoryscan           | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar               | None                                     |
	| LCHIJA | thaumicperiphery          | 0.3.0                    | thaumicperiphery-0.3.0.jar                               | None                                     |
	| LCHIJA | tinkersjei                | 1.2                      | tinkersjei-1.2.jar                                       | None                                     |
	| LCHIJA | tinkertoolleveling        | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                      | None                                     |
	| LCHIJA | tombstone                 | 3.5.5                    | tombstone-3.5.5-1.12.jar                                 | None                                     |
	| LCHIJA | topaddons                 | 1.12.2-1.11.0            | topaddons-1.12.2-1.11.0.jar                              | None                                     |
	| LCHIJA | traverse                  | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                             | None                                     |
	| LCHIJA | v0idssmartbackpacks       | 1.0.6                    | V0id's Smart Backpacks-1.0.6.jar                         | None                                     |
	| LCHIJA | voidcraft                 | 0.26.10                  | VoidCraft-1.12-0.26.10.jar                               | None                                     |
	| LCHIJA | waystones                 | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                              | None                                     |
	| LCHIJA | wings                     | 1.1.5                    | wings-1.1.5-1.12.2.jar                                   | None                                     |
	| LCHIJA | bauble_wings              | 1.0.0                    | wings-1.1.5-1.12.2.jar                                   | None                                     |
	| LCHIJA | wct                       | 3.12.93                  | WirelessCraftingTerminal-1.12.2-3.12.93.jar              | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | wizardry                  | 0.10.8                   | wizardry-0.10.8.jar                                      | None                                     |
	| LCHIJA | librarianliblate          | 4.19.2                   | librarianlib-1.12.2-4.19.2-release.jar                   | None                                     |
	| LCHIJA | mysticallib               | 1.12.2-1.3.1             | mysticallib-1.12.2-1.3.1.jar                             | None                                     |
	| UD     | mobends_wings             | 1.0.0                    | wings-1.1.5-1.12.2.jar                                   | None                                     |

	Loaded coremods (and transformers): 
SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  pl.asie.splashanimation.core.SplashProgressTransformer
wings (wings-1.1.5-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
AALoadingPlugin (arcanearchives-0.2.0.1.jar)
  
Incorporeal Tweaker (incorporeal-1.1.4.jar)
  quaternary.incorporeal.spookyasm.IncorporealTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
HCASM (HammerCore-1.12.2-2.0.4.7.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
Quark Plugin (Quark-r1.6-174.jar)
  vazkii.quark.base.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.10-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
p455w0rdc0re (p455w0rdslib-1.12.2-2.2.156.jar)
  p455w0rdslib.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  
Wizardry Plugin (wizardry-0.10.8.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
Botania Tweaks Core (botaniatweaks-1.8.6.jar)
  quaternary.botaniatweaks.asm.BotaniaTweakerTransformer
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 4492 names; 5109 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Expanded Equivalence (expequiv) @12r

	[Psi] Active spell: None
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by asiekierka** [comment]
Update FoamFix.  Also, check if disabling coremod.fasterHopper fixes the problem.
