### ISSUE TITLE
Crash w/ Pandora's Box

### ISSUE THREAD

**Issue by WenXin20** [asiekierka/FoamFix#25]
Forge 2215
Foamfix v0.5.1 Anarchy
Pandora's Box v2.1.5
Ivtoolkit v1.2.9
I got this crash after picking up a pandora's box.
[Crash Log](http://pastebin.com/nzXE8bM7)

**Comment by asiekierka** [comment]
Does this not happen without FoamFix?

**Comment by WenXin20** [comment]
Ok, it looks like it still crashes without Foam Fix and is actually caused by Tough as Nails mod.
