### ISSUE TITLE
Causing problem with the codes in .bat file

### ISSUE THREAD

**Issue by linzexin022** [asiekierka/FoamFix#254]
I tested the brand new 1.15.2 server only with 2 mods, Fabric API and FoamFix (0.12.1 Ver.). I also pasted some codes recommended by others to try optimizing it. Then it said " Can't keep up! Is the server overloaded? Running 2255ms or 45 ticks behind" which doesn't happen either with those codes or with those 2 mods. I think maybe some codes conflict but don't know which caused the problem.

I pasted : "java -Xms8G -Xmx8G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled  -XX:+UseLargePagesInMetaspace -Dusing.aikars.flags=mcflags.emc.gs -jar fabric-server-launch.jar nogui" in .bat file, and also tested with "-Xmx2G -Xms2G", which remained the same result.. I would be grateful if you could tell me which code conflicts.

**Comment by asiekierka** [comment]
FoamFix for Fabric was only released for 1.14.
