### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by ItsJustReap** [asiekierka/FoamFix#260]
So I am creating my own modpack and i had foam fix installed. I asked some people in a discord server and sent them my logs and stuff. they said its foam fix so i deleted it and it works now. 1 guy in there said i should report it so i did here are my files
[hs_err_pid81228.log](https://github.com/asiekierka/FoamFix/files/4603357/hs_err_pid81228.log)

**Comment by jadenquinn** [comment]
Try changing your Java version to 1.8.0_252. I tried that with vanilla and it didn't randomly crash anymore.
Mojang should just update it once in a great while.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/258
