### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by jasonisop** [asiekierka/FoamFix#261]
You may wise to review the license you picked to use for your project.  
People can alter and upload their own versions of your code as well as charge for it if they wish. 

https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by asiekierka** [comment]
I'm well aware of what the license I used for my code says. As a developer and computer user, I rely heavily on free software; why would I not contribute back?

**Comment by skyem123** [comment]
Also since this is a Minecraft mod, charging for it would probably be against the Minecraft EULA...
