### ISSUE TITLE
crash by  java.lang.IncompatibleClassChangeError: Class net.minecraft.world.WorldServer does not implement the requested interface pl.asie.foamfix.coremod.patches.IFoamFixWorldRemovable

### ISSUE THREAD

**Issue by leonpano2006** [asiekierka/FoamFix#263]
[crash-2020-10-25_18.20.19-server.txt](https://github.com/asiekierka/FoamFix/files/5435482/crash-2020-10-25_18.20.19-server.txt)

**Comment by asiekierka** [comment]
... That's a new one! Do you have a full client launch log?

**Comment by leonpano2006** [comment]
Actually I think I don’t need help now
It was two months ago
And I already forgot what happened
