### ISSUE TITLE
Modpack Crashes

### ISSUE THREAD

**Issue by AefRal** [asiekierka/FoamFix#264]
I've been updating mods trying to get this pack to work again, and I've hit a wall.
I can't understand crash reports, don't have the technical know-how to read them and know what's wrong, so...
Help?

"The game crashed whilst initializing game
Error: java.lang.NoSuchFieldError: field_185198_a
Exit Code: -1"

[crash-2020-10-26_02.11.15-client.txt](https://github.com/asiekierka/FoamFix/files/5437604/crash-2020-10-26_02.11.15-client.txt)

**Comment by asiekierka** [comment]
Not related to FoamFix, may be related to old mod and/or Forge versions. Certainly, the version of FoamFix is pretty old.
