### ISSUE TITLE
[Crash] spontaneous crash for unknown reasons with PrimalCore (according to VanillaFix)

### ISSUE THREAD

**Issue by gatoborrachon** [asiekierka/FoamFix#266]
well, i can't say much, it just happens, it happened 2 times since i play with both mods (idk when i started), its pretty rare but anyways i can post the issue wishing for an answer:
Forge: 1.12.2-forge-14.23.5.2854
FoamFix: 0.10.10
PrimalCore: 0.6.105

https://pastebin.com/w13S62gs

**Comment by asiekierka** [comment]
To my knowledge, this is not a FoamFix-specific bug.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/267

**Comment by gatoborrachon** [comment]
oh, many thanks for answer, and yeah i'm using the latest forge version, i don't think this will be possible fixed from PrimalCore's side since the mod is dead (i got the same crash 3 days ago), but i know this is not your fault, so there's np, anyways i'm going to open an issue in their issue tracker just for formality

**Comment by gatoborrachon** [comment]
Hey asie, i know that this issue is not your problem, but you know how to fix it after it happens? 

i used NBTExplorer to delete the EntityItem and it doesn't worked (i think it is because it corrupts the Block_Water where the EntityItem was droped), but when i deleted the chunk it fixed the issue, so, you may know how to delete a specific WaterBlock outside minecraft? (i can't find a way with NBTExplorer)
