### ISSUE TITLE
Causing issues in a modpack I made

### ISSUE THREAD

**Issue by minhtet-htoon** [asiekierka/FoamFix#272]
I'm using a custom mod pack for a server with a group of friends. I am not sure what ppl were doing when the error was thrown nor who caused it. All I know is that removing FoamFix fixed the problem. It worked for about a week on this server. It kept memory and CPU usage down so I'd like to continue using it. Please help. The pack has about 75 mods.
I have attached the crash report.
[crash-2021-03-19_14.19.15-client.txt](https://github.com/asiekierka/FoamFix/files/6178020/crash-2021-03-19_14.19.15-client.txt)

**Comment by asiekierka** [comment]
Crash while drawing a recipe, due to a mod providing an Item without a corresponding registry entry.

I fail to see how FoamFix is related. Could you try to narrow it down to a foamfix.cfg option?

**Comment by minhtet-htoon** [comment]
I'm not quite sure what happened either but the server nor the client has crashed for over a month now. my guess is that it might be an error elsewhere and a coincidence that it worked when i removed the mod. It crashed when we loaded a new dimension while a buddy was compressing cobblestone for the meme. I guess the server just crashed bc lag so I'll close this issue.
