### ISSUE TITLE
FoamFix-1.7.10-universal-1.0.0-beta2 crash with techguns when casting ArrowDingTweakEventHandler

### ISSUE THREAD

**Issue by brandyyn** [asiekierka/FoamFix#273]
[crash-2021-05-14_23.15.08-server.txt](https://github.com/asiekierka/FoamFix/files/6481405/crash-2021-05-14_23.15.08-server.txt)
[latest - Copy.log](https://github.com/asiekierka/FoamFix/files/6481407/latest.-.Copy.log)

I'm guessing this 
" # Emits a 'ding' sound when mobs are hit by an arrow, not just players. (from BugfixMod by williewillus)
    B:arrowDing=false"

fixes it, however I was just standing still in singleplayer when it happened, so I thought I should report it anyway. Close it if it's a non-issue.

**Comment by asiekierka** [comment]
Valid bug, will fix!

**Comment by asiekierka** [comment]
Fixed in 1.0.0-beta3. Going forward, please report 1.7.10 bug reports to https://github.com/asiekierka/FoamFix17 .
