### ISSUE TITLE
[0.10.12a] Redstone dust not rendering after mod update

### ISSUE THREAD

**Issue by xJon** [asiekierka/FoamFix#275]
Caused after updating from `0.10.11`, not using Optifine, can reproduce with only FoamFix installed.
Originally reported to my modpack over https://github.com/xJon/The-1.12.2-Pack/issues/681.
Weird, huh?

**Comment by SanAndreaP** [comment]
I have the same issue, disabling `client.smallModelConditions` fixes it for me.

**Comment by Derkades** [comment]
some more info in case it helps
![2021-05-25_22 40 00](https://user-images.githubusercontent.com/15892014/119565434-3834b380-bdaa-11eb-92b8-0dc2f3f81db9.png)

**Comment by nyyakko** [comment]
having the same issue here. but instead of changing `client.smallModelConditions` to fix the problem, i decided just to downgrade back to 0.10.11.

**Comment by VerySaltyOreos** [comment]
0.10.12 and 0.10.12a cause the fire texture/model and some other textures from different mods to break/disappear. 
Reverting to 0.10.11 fixes this, meaning it's specifically the newest ones.
Didn't know it was doing this to redstone too.

**Comment by xJon** [comment]
This seems to be resolved with version [`0.10.14`](https://www.curseforge.com/minecraft/mc-mods/foamfix-optimization-mod/files/3327893).
EDIT: This issue still isn't resolved - https://github.com/asiekierka/FoamFix/issues/276.
