### ISSUE TITLE
Conflict with PureBDCraft

### ISSUE THREAD

**Issue by Swandar** [asiekierka/FoamFix#276]
My modlist
![image](https://user-images.githubusercontent.com/19779837/119298182-83c05380-bc2a-11eb-80f8-8c7abf4d126c.png)

My log
[2021-04-10-2.log.gz](https://github.com/asiekierka/FoamFix/files/6529886/2021-04-10-2.log.gz)

A problem occurred while running Foamfix alongside PureBDCraft. All the grassblocks in the world vanish like an x-ray pack is enabled.

I've not thoroughly tested it yet, I spent a little over an hour just trying to identify the problem, it was there when I last played. So it was most likely an update, possibly on your end or another mod like Optifine, that caused this issue. I'm presuming that Optifine is most likely the culprit, but atm I am too tired to do further investigation. When I wake up in about 8 hours I will attempt to do some testing but until then Gute Nacht

EDIT: This is just a test pack for a mini-game I'm making

**Comment by xJon** [comment]
Perhaps setting `smallModelConditions` to `false` might help help.

**Comment by Swandar** [comment]
> Perhaps setting `smallModelConditions` to `false` might help help.

I wish I could understand half the shit in the configs. That fixed the issue, thank you kindly

**Comment by xJon** [comment]
No worries, this was probably caused by a bug from the latest update, also related to https://github.com/asiekierka/FoamFix/issues/275. I only knew of this workaround thanks to @SanAndreasP's comment there.

**Comment by xJon** [comment]
This should probably be reopened as it's still a bug in the mod and it was not fixed in version [`0.10.14`](https://www.curseforge.com/minecraft/mc-mods/foamfix-optimization-mod/files/3327893).
