### ISSUE TITLE
Latest version of Foamfix for 1.12, reverting to an older version fixes.

### ISSUE THREAD

**Issue by dazadazu** [asiekierka/FoamFix#277]
A plant from the prehistoric flora mod.

![Untitled](https://user-images.githubusercontent.com/73519218/121840832-efc63280-cc91-11eb-878f-9e61e306b33e.png)

**Comment by dazadazu** [comment]
It also makes ZAWA mobs invisible, removing foamfix fixes that. 1.12

**Comment by CrimsonTheWanderer** [comment]
I had the same issue, except with regular Grass Blocks and Wood Slabs/Stairs.
![2021-06-19_18 39 06](https://user-images.githubusercontent.com/86215510/122701713-109b0480-d20b-11eb-8711-e8b72bd98323.png)

**Comment by CrimsonTheWanderer** [comment]
Only was an issue for 1.10.14, but 1.10.10 works just fine.

**Comment by AechtRob** [comment]
It has been reported on my mod that setting FoamFix B:deduplicate=false fixes the issue in the top screenshot here.

**Comment by WolfBV** [comment]
Fucked around with all dem settings. You only have to change one thing in the config to fix that top pic. 

Change

 More optimized multipart model condition storage. Inspired by malte0811's research. [default: true]
    B:smallModelConditions=true

to

 More optimized multipart model condition storage. Inspired by malte0811's research. [default: true]
    B:smallModelConditions=false
