### ISSUE TITLE
[1.7.10] MorePlayerModels crashes with 1.0.0.

### ISSUE THREAD

**Issue by MagmaSlime123** [asiekierka/FoamFix#281]
See title.

[crash-2021-12-11_15.53.04-client.txt](https://github.com/asiekierka/FoamFix/files/7697850/crash-2021-12-11_15.53.04-client.txt)

FoamFix-1.7.10-universal-1.0.0 and MorePlayerModels_1.7.10b.

**Comment by JohnsonJohnsonson** [comment]
Try to set the line

`B:mc18SkinSupport`

in foamfix.cfg from "true" to "false". MPM wasn't made with the new skin format in mind - a lot of mods weren't. Off the top of my head, this will cause cause issues with Twilight Forest and Botania, as both have enemies that use your skin which will be messed up if the png is arranged differently.

**Comment by MagmaSlime123** [comment]
Works.

**Comment by cmbgcode** [comment]
> Try to set the line
> 
> `B:mc18SkinSupport`
> 
> in foamfix.cfg from "true" to "false". MPM wasn't made with the new skin format in mind - a lot of mods weren't. Off the top of my head, this will cause cause issues with Twilight Forest and Botania, as both have enemies that use your skin which will be messed up if the png is arranged differently.

Writing just to thank this and also inform about it. (Using 1.0.0)

Had a similar problem with different armor stands from different mods (not a crash but a texture annoyance).
Steve textures were appearing in some parts of the armor. 
The texture arrangement part makes a lot of sense, and that support in the config being "true" was the problem. Thank you.

![2022-07-21_12 32 54](https://user-images.githubusercontent.com/87330176/180254070-96143e1b-5258-4ef0-b650-674508c2fcc5.png)

(could be some other mod conflicting with this one, not entirely sure, wanted to inform anyways.)
