### ISSUE TITLE
[1.12.2] crash-report

### ISSUE THREAD

**Issue by Karfagenych** [asiekierka/FoamFix#282]
`---- Minecraft Crash Report ----
// My bad.

Time: 2022-01-11 17:58:27 VLAT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'CMINP7'.
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:136)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
    at pro.gravit.launcher.DalCrAFT9nQNVD.daLcrafTb7NnnF(Unknown Source)
    at pro.gravit.launcher.DalCrAFT9nQNVD.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'CMINP7'.
    at net.minecraft.scoreboard.Scoreboard.removePlayerFromTeam(SourceFile:270)
    at net.minecraft.client.network.NetHandlerPlayClient.handleTeams(NetHandlerPlayClient.java:2028)
    at net.minecraft.network.play.server.SPacketTeams.processPacket(SourceFile:117)
    at net.minecraft.network.play.server.SPacketTeams.processPacket(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_311, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5423062704 bytes (5171 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 8 total; -XX:+DisableAttachMechanism -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms8192M -Xmx8192M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 88 mods loaded, 88 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version                  | Source                                          | Signature                                |
       |:------ |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                  | 8.0.99.99                | forge.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2860             | forge.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | betterfonts          | 1.9.1                    | minecraft.jar                                   | None                                     |
       | LCHIJA | foamfixcore          | 7.7.4                    | minecraft.jar                                   | None                                     |
       | LCHIJA | itemblacklist        | 1.4.3                    | Server-ItemBlacklist.jar                        | None                                     |
       | LCHIJA | customloadingscreen  | 1.12.2-1.4.2-pre.12      | Client-CustomLoadingScreen.jar                  | None                                     |
       | LCHIJA | durabilityshow       | 5.0.0                    | Client-DurabilityShow.jar                       | None                                     |
       | LCHIJA | sereneseasons        | 1.2.18                   | Server-SereneSeasons.jar                        | None                                     |
       | LCHIJA | orelib               | 3.6.0.1                  | Library-OreLib.jar                              | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround            | 3.6.1.0                  | Client-DynamicSurroundings.jar                  | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | foamfix              | 0.10.14-1.12.2           | Client-FoamFix.jar                              | None                                     |
       | LCHIJA | gendustryjei         | 1.0.2                    | Client-GendustryJEI.jar                         | None                                     |
       | LCHIJA | waila                | 1.8.26                   | Client-Hwyla.jar                                | None                                     |
       | LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | Client-InventoryTweaks.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | forgelin             | 1.8.4                    | Library-Forgelin.jar                            | None                                     |
       | LCHIJA | alib                 | 1.0.12                   | Library-Alib.jar                                | None                                     |
       | LCHIJA | alchemistry          | 1.12.2-42                | Server-Alchemistry.jar                          | None                                     |
       | LCHIJA | jei                  | 4.16.1.301               | Client-JEI.jar                                  | None                                     |
       | LCHIJA | reborncore           | 3.19.5                   | Library-RebornCore.jar                          | None                                     |
       | LCHIJA | codechickenlib       | 3.2.3.358                | Library-CodeChickenLib.jar                      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux         | 2.1.1                    | Library-RedstoneFlux.jar                        | None                                     |
       | LCHIJA | cofhcore             | 4.6.6                    | Library-CoFHCore.jar                            | None                                     |
       | LCHIJA | cofhworld            | 1.4.0                    | Library-CoFHWorld.jar                           | None                                     |
       | LCHIJA | thermalfoundation    | 2.6.7                    | Server-ThermalFoundation.jar                    | None                                     |
       | LCHIJA | thermalexpansion     | 5.5.7                    | Server-ThermalExpansion.jar                     | None                                     |
       | LCHIJA | techreborn           | 2.27.3.1084              | Server-TechReborn.jar                           | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | forestry             | 5.8.2.387                | Server-Forestry.jar                             | None                                     |
       | LCHIJA | jeibees              | 0.9.0.5                  | Client-JEIbees.jar                              | None                                     |
       | LCHIJA | jeiintegration       | 1.6.0                    | Client-JEIIntegration.jar                       | None                                     |
       | LCHIJA | journeymap           | 1.12.2-5.7.1             | Client-Journeymap.jar                           | None                                     |
       | LCHIJA | jeresources          | 0.9.2.60                 | Client-JustEnoughResources.jar                  | None                                     |
       | LCHIJA | mousetweaks          | 2.10                     | Client-MouseTweaks.jar                          | None                                     |
       | LCHIJA | neat                 | 1.4-17                   | Client-Neat.jar                                 | None                                     |
       | LCHIJA | overpoweredarmorbar  | @VERSION@                | Client-OverloadedArmorbar.jar                   | None                                     |
       | LCHIJA | particleculling      | 1.0                      | Client-Particleculling.jar                      | None                                     |
       | LCHIJA | sshud                | 1.0                      | Client-SSHUD.jar                                | None                                     |
       | LCHIJA | mantle               | 1.12-1.3.3.55            | Library-Mantle.jar                              | None                                     |
       | LCHIJA | tconstruct           | 1.12.2-2.13.0.183        | Server-TConstruct.jar                           | None                                     |
       | LCHIJA | tinkersjei           | 1.2                      | Client-TinkersJEI.jar                           | None                                     |
       | LCHIJA | treechopper          | 1.2.4                    | Client-TreeChopper.jar                          | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-150               | Client-VanillaFix.jar                           | None                                     |
       | LCHIJA | wailaharvestability  | 1.1.12                   | Client-WailaHarvestability.jar                  | None                                     |
       | LCHIJA | wawla                | 2.6.275                  | Client-Wawla.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | worldeditcuife3      | 3.0.9                    | Client-WorldEdit-CUI.jar                        | None                                     |
       | LCHIJA | applecore            | 3.4.0                    | Library-AppleCore.jar                           | None                                     |
       | LCHIJA | bdlib                | 1.14.3.12                | Library-bdlib.jar                               | None                                     |
       | LCHIJA | bspkrscore           | 8.0.0                    | Library-bspkrscore.jar                          | None                                     |
       | LCHIJA | collective           | 3.0                      | Library-collective.jar                          | None                                     |
       | LCHIJA | libnine              | 1.2.0                    | Library-Libnine.jar                             | None                                     |
       | LCHIJA | neid                 | 1.5.4.4                  | Library-NotEnoughIDs.jar                        | None                                     |
       | LCHIJA | patchouli            | 1.0-23.6                 | Library-Patchouli.jar                           | None                                     |
       | LCHIJA | resourceloader       | 1.5.3                    | Library-Resourceloader.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | wanionlib            | 1.12.2-2.5               | Library-WanionLib.jar                           | None                                     |
       | LCHIJA | appliedenergistics2  | rv6-stable-7             | Server-AppliedEnergistics2.jar                  | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | chickenchunks        | 2.4.2.74                 | Server-ChickenChunks.jar                        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cookingforblockheads | 6.5.0                    | Server-CookingForBlockheads.jar                 | None                                     |
       | LCHIJA | dupefixproject       | 3.1.2                    | Server-DupeFixProject.jar                       | None                                     |
       | LCHIJA | energyconverters     | 1.3.7.30                 | Server-EnergyConverters.jar                     | None                                     |
       | LCHIJA | gendustry            | 1.6.5.8                  | Server-Gendustry.jar                            | None                                     |
       | LCHIJA | immersiveengineering | 0.12-98                  | Server-ImmersiveEngineering.jar                 | None                                     |
       | LCHIJA | immersivecables      | 1.3.2                    | Server-ImmersiveCables.jar                      | None                                     |
       | LCHIJA | immersivepetroleum   | 1.1.10                   | Server-ImmersivePetroleum.jar                   | None                                     |
       | LCHIJA | ironchest            | 1.12.2-7.0.67.844        | Server-IronChest.jar                            | None                                     |
       | LCHIJA | magicbees            | 1.0                      | Server-MagicBees.jar                            | None                                     |
       | LCHIJA | immersivetech        | 1.8.94                   | Server-MCTImmersiveTechnology.jar               | None                                     |
       | LCHIJA | mekanism             | 1.12.2-9.8.3.390         | Server-Mekanism.jar                             | None                                     |
       | LCHIJA | mekanismfluxified    | 1.0.0                    | Server-MekanismFluxified.jar                    | None                                     |
       | LCHIJA | mekanismgenerators   | 1.12.2-9.8.3.390         | Server-MekanismGenerators.jar                   | None                                     |
       | LCHIJA | mekanismtools        | 1.12.2-9.8.3.390         | Server-MekanismTools.jar                        | None                                     |
       | LCHIJA | nuclearcraft         | 2.18z                    | Server-NuclearCraft.jar                         | None                                     |
       | LCHIJA | mekores              | 2.0.13                   | Server-Mekores.jar                              | None                                     |
       | LCHIJA | examplemod           | 1.0                      | Server-NuclearCraft.jar                         | None                                     |
       | LCHIJA | nutrition            | 4.6.1                    | Server-Nutrition.jar                            | None                                     |
       | LCHIJA | getalltheseeds       | 1.12a                    | Server-Pam's Get all the Seeds.jar              | None                                     |
       | LCHIJA | harvestcraft         | 1.12.2zb                 | Server-Pam's HarvestCraft.jar                   | None                                     |
       | LCHIJA | pamscookables        | 1.1                      | Server-PamsCookables.jar                        | None                                     |
       | LCHIJA | roughmobs            | 2.0.0                    | Server-RoughMobs2.jar                           | None                                     |
       | LCHIJA | thermaldynamics      | 2.5.6                    | Server-ThermalDynamics.jar                      | None                                     |
       | LCHIJA | tinkersaddons        | 1.0.7                    | Server-Tinkers' Addons.jar                      | None                                     |
       | LCHIJA | tcomplement          | 1.12.2-0.4.3             | Server-TinkersComplement.jar                    | None                                     |
       | LCHIJA | tconevo              | 1.0.44                   | Server-TinkersEvolution.jar                     | None                                     |
       | LCHIJA | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | Server-TinkerToolLeveling.jar                   | None                                     |
       | LCHIJA | phosphor-lighting    | 1.12.2-0.2.6             | Client-Phosphor.jar                             | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | techreborn_compat    | 1.0.0                    | TechReborn-ModCompatibility-1.12.2-1.4.0.76.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | hungeroverhaul       | 1.12.2-1.3.3.jenkins148  | Server-HungerOverhaul.jar                       | None                                     |
       | LCHIJA | unidict              | 1.12.2-3.0.8             | Server-UniDict.jar                              | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (Client-FoamFix.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      ClsPlugin (Client-CustomLoadingScreen.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      TransformLoader (Client-DynamicSurroundings.jar)
                                        
                                      TconEvoCoreMod (Server-TinkersEvolution.jar)
                                        xyz.phanta.tconevo.coremod.TconEvoClassTransformer
                                      VanillaFixLoadingPlugin (Client-VanillaFix.jar)
                                        
                                      BetterFontsCore (Client-TTFR.jar)
                                        cubex2.ttfr.BFClassTransformer
                                      ParticleCullingLoadingPlugin (Client-Particleculling.jar)
                                        
                                      LoadingPlugin (Library-Resourceloader.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      Inventory Tweaks Coremod (Client-InventoryTweaks.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      MekanismCoremod (Server-Mekanism.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      SSLoadingPlugin (Server-SereneSeasons.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      DupeFixProjectCoreMod (Server-DupeFixProject.jar)
                                        
                                      AppleCore (Library-AppleCore.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ForgelinPlugin (Library-Forgelin.jar)
                                        
                                      PhosphorFMLLoadingPlugin (Client-Phosphor.jar)
                                        
                                      Plugin (Library-NotEnoughIDs.jar)
                                        ru.fewizz.neid.asm.Transformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 497.29' Renderer: 'NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ModuleSteelworks (Enabled/Not Forced)
                                    - ToolLevelingPlugin (Enabled/Not Forced)
                                    - Oredict (Enabled/Forced)
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.19.5
              Runtime Debofucsation 1
              Invalid fingerprint detected for RebornCore!
              RenderEngine: 1
  List of loaded APIs: * AppleCoreAPI (3.4.0) from Library-AppleCore.jar
                       * appliedenergistics2|API (rv6) from Server-AppliedEnergistics2.jar
                       * cofhapi (2.5.0) from Library-CoFHCore.jar
                       * ForestryAPI|apiculture (5.0.0) from Server-Forestry.jar
                       * ForestryAPI|arboriculture (4.3.0) from Server-Forestry.jar
                       * ForestryAPI|book (5.8.1) from Server-Forestry.jar
                       * ForestryAPI|circuits (3.1.0) from Server-Forestry.jar
                       * ForestryAPI|climate (5.0.0) from Server-Forestry.jar
                       * ForestryAPI|core (5.7.0) from Server-Forestry.jar
                       * ForestryAPI|farming (5.8.0) from Server-Forestry.jar
                       * ForestryAPI|food (1.1.0) from Server-Forestry.jar
                       * ForestryAPI|fuels (3.0.0) from Server-Forestry.jar
                       * ForestryAPI|genetics (5.7.0) from Server-Forestry.jar
                       * ForestryAPI|gui (5.8.0) from Server-Forestry.jar
                       * ForestryAPI|hives (4.1.0) from Server-Forestry.jar
                       * ForestryAPI|lepidopterology (1.4.0) from Server-Forestry.jar
                       * ForestryAPI|mail (3.1.0) from Server-Forestry.jar
                       * ForestryAPI|modules (5.7.0) from Server-Forestry.jar
                       * ForestryAPI|multiblock (3.0.0) from Server-Forestry.jar
                       * ForestryAPI|recipes (5.4.0) from Server-Forestry.jar
                       * ForestryAPI|storage (5.0.0) from Server-Forestry.jar
                       * ForestryAPI|world (2.1.0) from Server-Forestry.jar
                       * gendustryAPI (2.3.0) from Server-Gendustry.jar
                       * ImmersiveEngineering|API (1.0) from Server-ImmersiveEngineering.jar
                       * ImmersiveEngineering|ImmersiveFluxAPI (1.0) from Server-ImmersiveEngineering.jar
                       * jeresources|API (0.9.2.60) from Client-JustEnoughResources.jar
                       * journeymap|client-api (1.4) from Client-Journeymap.jar
                       * journeymap|client-api-display (1.4) from Client-Journeymap.jar
                       * journeymap|client-api-event (1.4) from Client-Journeymap.jar
                       * journeymap|client-api-model (1.4) from Client-Journeymap.jar
                       * journeymap|client-api-util (1.4) from Client-Journeymap.jar
                       * JustEnoughItemsAPI (4.13.0) from Client-JEI.jar
                       * MekanismAPI|core (9.8.1) from Server-Mekanism.jar
                       * MekanismAPI|energy (9.8.1) from Server-Mekanism.jar
                       * MekanismAPI|gas (9.8.1) from Server-Mekanism.jar
                       * MekanismAPI|infuse (9.8.1) from Server-Mekanism.jar
                       * MekanismAPI|laser (9.8.1) from Server-Mekanism.jar
                       * MekanismAPI|transmitter (9.8.1) from Server-Mekanism.jar
                       * MekanismAPI|util (9.0.0) from Server-Mekanism.jar
                       * MouseTweaks|API (1.0) from Client-MouseTweaks.jar
                       * PatchouliAPI (6) from Library-Patchouli.jar
                       * reborncoreAPI (3.19.5) from Library-RebornCore.jar
                       * reborncoreAPI|Power (3.19.5) from Library-RebornCore.jar
                       * reborncoreAPI|Recipe (3.19.5) from Library-RebornCore.jar
                       * reborncoreAPI|Tile (3.19.5) from Library-RebornCore.jar
                       * redstonefluxapi (2.1.1) from Library-RedstoneFlux.jar
                       * team_reborn|Praescriptum (3.19.5) from Library-RebornCore.jar
                       * techrebornAPI (2.27.3.1084) from Server-TechReborn.jar
                       * WailaAPI (1.3) from Client-Hwyla.jar
  Patchouli open book context: n/a
  AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
  Suspected Mods: FoamFixCore (foamfixcore)`

**Comment by asiekierka** [comment]
You're using an unofficial, proprietary launcher which obfuscates its code. This is not supported.
