### ISSUE TITLE
Your mod ruined my world LOL

### ISSUE THREAD

**Issue by dylaonlsd** [asiekierka/FoamFix#287]
Your trash mod for some reason crashes my pixelmon world (forestry is the issue also) because they arent compatible. But i cant disable foamfix because its not my mod pack. I mined some leaves with a leech 2 axe and it crashed my game. gave me an item that crashes my game over and over again when i try to open my inventory. then i die and destroy my gravestone and the whole Lan world crashes. IDK WHAT TO DO OR HOW TO FIX IT the only solution is to delete your shitty mod

**Comment by spectrapulse** [comment]
The mod isn't shitty lmao

Also neither is your issue helpful or providing any logs

**Comment by sylbeth** [comment]
> for some reason crashes my pixelmon world (forestry is the issue also) because they arent compatible

Dude, it's literally in the Pixelmon incompatibilities. If you wanna complain, don't post an issue. If you do wanna help the log is necessary. Is this your first time posting an issue? Because you really should touch some grass and calm down before any of this.

**Comment by spectrapulse** [comment]
> > for some reason crashes my pixelmon world (forestry is the issue also) because they arent compatible
> 
> Dude, it's literally in the Pixelmon incompatibilities. If you wanna complain, don't post an issue. If you do wanna help the log is necessary. Is this your first time posting an issue? Because you really should touch some grass and calm down before any of this.

lol my man made a github account just to shit on this project

**Comment by asiekierka** [comment]
As per the licensing terms, under which you are granted rights pertaining to the mod:

```
FoamFix is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
```

Please report this issue to the modpack developer; they might "know what to do", which then may lead me to find out "how to fix it".
