### ISSUE TITLE
1.14.4

### ISSUE THREAD

**Issue by ghost** [asiekierka/FoamFix#293]
I am creating a modpack to have 60+ fps (similar to fabulously optimized) but for 1.14.4, I wanted to know if you can make a 1.14.4 version of this mod but for Forge

Here is list of mods, its incomplete
![mods](https://user-images.githubusercontent.com/114604732/196812321-eae5a9a0-c948-4a4e-9b63-09865f86f9a4.PNG)

And sorry for my bad english but i do all i can

Edit: I need this so that the minecraft does not crash due to the out of memory error

**Comment by asiekierka** [comment]
No plans at the moment. I recommend using an alternate mod, like FerriteCore.
