### ISSUE TITLE
Backport to 1.7.10

### ISSUE THREAD

**Issue by owenthewizard** [asiekierka/FoamFix#32]
Would it be possible to backport this to Minecraft 1.7.10?

**Comment by asiekierka** [comment]
No point in doing so, FastCraft does a great job and many of FoamFix's optimizations are 1.8+-specific.

**Comment by asiekierka** [comment]
There is a FoamFix out for 1.7.10 now, but it's not really focused on memory optimization. It does share one category of fix with modern-day (1.12.2) FoamFix, though.
