### ISSUE TITLE
Issues with Bibliocraft models losing position/facing when unloading/loading chunks. (Anarchy 0.5.4)

### ISSUE THREAD

**Issue by ate0ate** [asiekierka/FoamFix#33]
I noticed that when using Foamfix Anarchy 0.5.4 that sometimes when I roam away from my base and return that all of my Bibliocraft blocks have changed facings, appear to have lost their contents, and returned to individual blocks if they were multiblocks. Heres some before and after pics to more clearly demonstrate what I mean...

http://imgur.com/a/5zpkV

Not sure if this is truly a Foamfix issue or if it is an issue with Bibliocraft, but I can say that using Foamfix Anarchy 0.5.3 this does not occur. Also this is all using forge 12.18.3.2221. Thanks!

**Comment by asiekierka** [comment]
Please try disabling coremod.optimizedBlockInfo.

**Comment by ate0ate** [comment]
That seems to have fixed the issue with the Bibliocraft blocks, but now I noticed another problem. My flux points from Flux Networks seem to not function properly upon world load. I have to break and replace them each time to get them to work properly. It only seems to happen with certain blocks though, most notably the Refined Storage Controller. The Flux point looks connected, but the Controller receives no power until I break and replace the Flux Point. I just tested and this does not happen with 0.5.3 only 0.5.4. It only seems to be on world load though. Very strange issues indeed.

**Comment by asiekierka** [comment]
If that is disabled, 0.5.4 *is* effectively 0.5.3 with unrelated rendering bugfixes. Very strange.

**Comment by ate0ate** [comment]
After Lots of testing I would say to disregard the whole Flux Point, Refined Storage Controller issue. Definitely not the fault of foamfix at all. It behaves oddly and appeared inconsistent between versions 0.5.4 and 0.5.3, but I have managed to repeat the issue in both versions now, fairly reliably. The bibliocraft block issue however is definitely related to the changes made in 0.5.4 and is the only issue I have found thus far. I will just leave the optimizedBlockInfo flag set to false for the time being as a workaround. Thank you.

**Comment by asiekierka** [comment]
I cannot reproduce this issue on the latest Git version.

**Comment by ate0ate** [comment]
Do you mean the .0.6.0 beta? I will try that if so.

**Comment by ate0ate** [comment]
I do not seem to experience any issues with the Bibliocraft blocks in the 0.6.0beta. The flux point issue was a bug on their end that has been addressed so I apologize for even bringing that up. One of those random bugs that randomly occurs in a not so random pattern for a bit. I only did some very brief testing of your beta build, but all appears to be well so far. Thanks for the time and patience.
