### ISSUE TITLE
FoamFix 0.6.0 breaks Optifine CTM

### ISSUE THREAD

**Issue by mrAppleXZ** [asiekierka/FoamFix#34]
FoamFix 0.6.0 beta 3.
Optifine HD U D6
MC 1.10.2
Forge 12.18.3.2221
Log files: https://gist.github.com/mrAppleXZ/0511c48eb6e804196e47bbaff6d165ef
FoamFix 0.6.0 beta 3:
![2017-02-21_10 34 58](https://cloud.githubusercontent.com/assets/7630912/23152314/1e91cd7e-f823-11e6-8dfc-a446820a7c95.png)
FoamFix 0.5.4:
![2017-02-21_10 48 49](https://cloud.githubusercontent.com/assets/7630912/23152360/647ba3d2-f823-11e6-8b0b-533ef2d5029a.png)

**Comment by asiekierka** [comment]
Please try disabling coremod.dynamicItemModels.

**Comment by mrAppleXZ** [comment]
@asiekierka It's still not fixed.

**Comment by asiekierka** [comment]
@sp614x Any clue as to how this could happen? See https://github.com/asiekierka/FoamFix/blob/master/src/main/java/pl/asie/foamfix/client/FoamyItemLayerModel.java for reference

**Comment by mrAppleXZ** [comment]
@asiekierka Sorry. I made a typo. It no_t_ works.

**Comment by asiekierka** [comment]
*sigh*

@mrAppleXZ Could you please try installing FoamFix 0.6.0 (not beta3)?

**Comment by mrAppleXZ** [comment]
@asiekierka Not working.

**Comment by mrAppleXZ** [comment]
@asiekierka Any ideas?

**Comment by asiekierka** [comment]
@mrAppleXZ Try disabling client.deduplicateModels. (It's not good for your RAM, but it might give me a culprit)

**Comment by asiekierka** [comment]
@mrAppleXZ For now, downgrade to 0.5.3 - a link is available on the FoamFix website. I'll have a look myself.

**Comment by asiekierka** [comment]
@mrAppleXZ Issue found - disable client.fasterResourceLoading for now.

**Comment by mrAppleXZ** [comment]
@asiekierka OK, thanks! =)

**Comment by asiekierka** [comment]
Fixed in FoamFix 0.6.1
