### ISSUE TITLE
[1.10.2] Client start up crash: IllegalArgumentException

### ISSUE THREAD

**Issue by DeadSix27** [asiekierka/FoamFix#35]
Foamfix: 0.6.0-beta3
Forge: 1.10.2-forge1.10.2-12.18.3.2221
JEC: JustEnoughCalculation-1.10.2-2.5.0.jar

Client crashes on startup, possible JustEnoughCalculation incompat.?

Posted this on both issue trackers, as I'm unsure which of both these mods causes this.

Other issue Link: https://github.com/Towdium/JustEnoughCalculation/issues/29

Stacktrace: http://pastebin.com/yTbmhzmL

**Comment by asiekierka** [comment]
Well, it *is* an incompatibility. Disable coremod.dynamicItemModels for the time being.

**Comment by DeadSix27** [comment]
@asiekierka Or just stay on 0.5.4 ?
Is there any groundbreaking changes from there to 0.6.0?

EDIT: `(Anarchy) Add support for dynamic baking of 3D item models on demand, saving RAM`
NVM!

**Comment by asiekierka** [comment]
@DeadSix27 Yes, until JustEnoughCalculation fixes the issue. Sorry - no other way around it.

**Comment by DeadSix27** [comment]
@asiekierka _I will just not use JEC  for a while :P_

**Comment by asiekierka** [comment]
I think it was fixed on their side?
