### ISSUE TITLE
High CPU Usage with chunkedBlockInfo enabled

### ISSUE THREAD

**Issue by DeadSix27** [asiekierka/FoamFix#36]
I just tested `foamfix-0.6.0-beta3-anarchy.jar` on my Server and ran into an issue.

CPU usage goes up quite quickly, also chunks seem to not load properly.
System is using 16GB RAM and an i7 6700k @ 4.6GHz.

_Compromise CPU usage for less memory? :p_

The RAM usage seems odd anyway, I tried finding out wether one of the mods leaks memory, but no success so far (8-12GB avg usage is a lot...)

### With `foamfix-0.6.0-beta3-anarchy.jar`
![cpu_mem](https://cloud.githubusercontent.com/assets/1492505/23163312/31c96230-f832-11e6-8783-8d0aea402a42.png)

### With `foamfix-0.5.4-anarchy.jar`:
![image](https://cloud.githubusercontent.com/assets/1492505/23163413/a173a3de-f832-11e6-8980-77fd489824a4.png)

**Comment by asiekierka** [comment]
1. Try disabling coremod.optimizedBlockInfo.
2. What is your mod list?

**Comment by DeadSix27** [comment]
1. disabling coremod.optimizedBlockInf fixes the high cpu usage, **so far** no chunks showed the not-loading issue. I will keep observing this.
2. Here's the mod list: https://share.dsix.tech/modlist.txt

**Comment by asiekierka** [comment]
Well then. Time to release 0.6.0-beta4 and disable optimizedBlockInfo by default.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/commit/497696098c70cefd11c1ff0df19ff34f1384643f

**Comment by Janitor53** [comment]
Will it work if I upgrade from previous version, or I need to delete old config manually?

**Comment by asiekierka** [comment]
Should work fine if you just upgrade.



--

  Adrian Siekierka

  kontakt@asie.pl







On Thu, Feb 23, 2017, at 08:05, Janitor53 wrote:

> Will it work if I upgrade from previous version, or I need to delete
> old config manually?
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
> 


Links:

  1. https://github.com/asiekierka/FoamFix/issues/36#issuecomment-281912446
