### ISSUE TITLE
Crash With Forestry

### ISSUE THREAD

**Issue by kenijey** [asiekierka/FoamFix#37]
https://github.com/ForestryMC/ForestryMC/issues/1627
this crash with foamfix 0.6.2 beta 2

**Comment by kenijey** [comment]
and version 0.6.1 works normally

**Comment by kenijey** [comment]
and ah, **version 0.6.1 also crashes** on server. but not with forestry, i couldn't understand what was the problem. see this crash report 
[crash-2017-03-14_22.04.20-server.txt](https://github.com/asiekierka/FoamFix/files/842430/crash-2017-03-14_22.04.20-server.txt)

**Comment by asiekierka** [comment]
Please disable coremod.fasterSideTransformer as a workaround.

**Comment by kenijey** [comment]
whoa, it worked!!!!!!! thanks.

**Comment by asiekierka** [comment]
This feature has been removed.
