### ISSUE TITLE
0.6.2 beta 2 and spongeforge

### ISSUE THREAD

**Issue by i9hdkill** [asiekierka/FoamFix#39]
When using foamfix in FTB Beyond + SpongeForge 2259, you will get an error at startup.

Whole log:
https://pastebin.com/iHrRhEHq

error at startup:
https://pastebin.com/Q2N3Z6wq

SpongeForge will still load fine, but something isn't quite right here and I man not sure, if it will cause issues.

https://github.com/SpongePowered/SpongeCommon/issues/1272

**Comment by asiekierka** [comment]
Try disabling optimizedBlockPos.

**Comment by i9hdkill** [comment]
Yep, error is gone, thanks!
