### ISSUE TITLE
foam fix failed to load

### ISSUE THREAD

**Issue by Potsukin** [asiekierka/FoamFix#4]
This is a log from my server console:

26.11 17:02:16 [Server] main/ERROR [FML]: Unable to read the jar file foamfix-0.3.2a-law.jar - ignoring

26.11 17:02:30 [Server] Server thread/WARN [FML]: Zip file foamfix-0.3.2a-law.jar failed to read properly, it will be ignored

What's happening?

**Comment by asiekierka** [comment]
It appears that the file might be corrupt. Not that it matters anyway,
because FoamFix is currently client-side only.

2016-11-27 0:24 GMT+01:00 Potsukin <notifications@github.com>:

**Comment by TheBrain0110** [comment]
Oh, it's client-only?
It might be good to mention that in your description somewhere. I was really hoping to save some memory usage on my server, since it's quite a bit more constrained than my desktop.

Any plans on adding server-side features?

**Comment by asiekierka** [comment]
I do plan into looking for further optimizations in 1.11, yes. I waited for
it to come out, in fact.

Generally, do not expect wonders for servers.

2016-12-06 17:21 GMT+01:00 TheBrain0110 <notifications@github.com>:
