### ISSUE TITLE
Crash (parallelModelBaking + FancyMissingModel)

### ISSUE THREAD

**Issue by kenijey** [asiekierka/FoamFix#42]
[crash-2017-04-04_18.37.08-client.txt](https://github.com/asiekierka/FoamFix/files/893672/crash-2017-04-04_18.37.08-client.txt)
it happened after updating 0.6.2 beta 2 to beta 3.

**Comment by asiekierka** [comment]
Ouch.

Disable parallel model baking for the time being.

**Comment by kenijey** [comment]
wheres that config? i couldn't find. is it this    B:deduplicateModels=true ?

**Comment by asiekierka** [comment]
B:parallelModelBaking

**Comment by asiekierka** [comment]
Does FoamFix 0.6.2-beta4 fix it? http://asie.pl/Projects/Minecraft/Mods/FoamFix/

**Comment by kenijey** [comment]
ok let me try

**Comment by kenijey** [comment]
okay it works fine now. thanks!
