### ISSUE TITLE
FoamFix 0.6.2 beta 4 "Anarchy" - Causes all trees to disappear!

### ISSUE THREAD

**Issue by viper2g1** [asiekierka/FoamFix#47]
All of the trees are invisible when adding this to a custom modpack version of FTB Beyond 1.4.2.  They used beta 3 which was unavailable at the time I updated my modpack so I used beta 4.  All trees were invisible and only showed an outline.  When I reverted to beta 2 the trees reappeared as normal.

This is an example of the issue
http://imgur.com/a/HPHl7

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/44
