### ISSUE TITLE
[1.11.2] Crash with integrated dynamics and TechReborn mods

### ISSUE THREAD

**Issue by Aphyxia** [asiekierka/FoamFix#49]
https://pastebin.com/4DxkffRf

Players on server tried connecting various integrated dynamics blocks and techreborn blocks and it resulted in a crash.

Tried with latest versions of the mods and libraries as of 15.04.2017 and also one step older techreborn mod and its library.

**Comment by asiekierka** [comment]
If you look at the history of closed issues, this type of issue appears very often and is usually not tied to FoamFix.

Please try to reproduce without FoamFix.

**Comment by Aphyxia** [comment]
True, it's also probably fixed as per https://github.com/CyclopsMC/IntegratedDynamics/issues/171
so I'll close this.
