### ISSUE TITLE
Report - Bad Interactions with Ternsip's StructPro Mod

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [asiekierka/FoamFix#51]
https://github.com/ternsip/StructPro/issues/16#issuecomment-296565166

**Comment by asiekierka** [comment]
Did you try to reproduce it without FoamFix?

**Comment by P3rf3ctXZer0** [comment]
I will do that right now. Sorry been busy the dev told me to report it.

**Comment by P3rf3ctXZer0** [comment]
@asiekierka I can confirm foam fix was most definitely the cause. At any rate I am not a coder just a testing dummy ;) so you will have to contact @ternsip to figure out why its having problems.

**Comment by ternsip** [comment]
```
at net.minecraft.world.chunk.BlockStateContainer.func_186008_a(BlockStateContainer.java:71)
	at net.minecraft.world.chunk.BlockStatePaletteLinear.func_186041_a(SourceFile:36)
	at net.minecraft.world.chunk.BlockStateContainer.func_186008_a(BlockStateContainer.java:71)
	at net.minecraft.world.chunk.BlockStatePaletteLinear.func_186041_a(SourceFile:36)
	at net.minecraft.world.chunk.BlockStateContainer.func_186008_a(BlockStateContainer.java:71)
	at net.minecraft.world.chunk.BlockStatePaletteLinear.func_186041_a(SourceFile:36)
	at net.minecraft.world.chunk.BlockStateContainer.func_186008_a(BlockStateContainer.java:71)
```
I can't imagine what cause such issue. My mod doens't affects minecraft native classes.

**Comment by asiekierka** [comment]
@ternsip Oh, if I could imagine what causes this, I'd probably have it fixed by now.

**Comment by P3rf3ctXZer0** [comment]
@asiekierka if it helps your information ... I tried 6.1 anarchy and lawful and both produced the same issue. I will start testing old versions of foamfix when I have the time. I noticed in life I seem to eerily good at finding obscure bugs.

**Comment by P3rf3ctXZer0** [comment]
@ternsip for the record using your schematic packs with recurrent complex foamfix has no problems. You may want to ask @Ivoforce for assistance in squashing this bug. He has a great wealth of knowledge in understanding the minecraft chunk and spawn algorithm and has re-wrote his mode twice to compensate.

**Comment by asiekierka** [comment]
@P3rf3ctXZer0 Lawful could *not* cause this - it doesn't edit Minecraft base code in any part related to worlds or block states.

**Comment by P3rf3ctXZer0** [comment]
This issue does not exist in 1.11.2 - Not sure if the will help. I am starting to test things a bunch. Also it did ... sorry if that confuses you but lawful also had the 1.10.2 crash ... I have no idea why ... At any rate I have jumped to 1.11.2 to see if the issues persist ... I may be forced to leave 1.10.2

**Comment by asiekierka** [comment]
Allegedly fixed.
