### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kenijey** [asiekierka/FoamFix#52]
in my dedicated server, i just typed /spawn to go to spawn. it doesn't crash when i spawn, it was just weird. i was on far away to spawn...
[crash-2017-04-28_18.49.34-client.txt](https://github.com/asiekierka/FoamFix/files/964845/crash-2017-04-28_18.49.34-client.txt)

**Comment by asiekierka** [comment]
Please read the Bug Reporting section of https://asie.pl/Projects/Minecraft/Mods/FoamFix/ and try to reproduce this without FoamFix.

**Comment by kenijey** [comment]
i can't reproduce it without foamfix, but i can't with foamfix too because it happened 1 time and after it i tried typing /spawn a few times but didn't happen as i said. then i'm closing this...
