### ISSUE TITLE
crash with AE2

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [asiekierka/FoamFix#54]
[crash-2017-05-20_19.55.12-client.txt](https://github.com/asiekierka/FoamFix/files/1016576/crash-2017-05-20_19.55.12-client.txt)

**Comment by asiekierka** [comment]
Nonono. That looks like an Optifine thing. Try without OptiFine and with FoamFix.

Assuming it's not OptiFine, did you try with Lawful? Did you try disabling options in the .cfg until it stops crashing?

**Comment by mgdgfbhevdyeh** [comment]
ok thanks asie.this crash is an Optifine thing
now i use Optifine 1.10.2 D6,all is work
and I try Foamfix Lanful with old Optifine,is should work,too.
