### ISSUE TITLE
Crash when both FoamFix and GalactiCraft are loaded

### ISSUE THREAD

**Issue by Eufranio** [asiekierka/FoamFix#55]
Crash-report: https://hastebin.com/yojovumuri.php
If you need any info just let me know.

**Comment by asiekierka** [comment]
I assume this does not happen without FoamFix?

If so, for a workaround, you can set B:smallPropertyStorage=false, but I'm really curious as to why this happens.

**Comment by Eufranio** [comment]
Yea, it doesn't happen without FoamFix. and disabling that option works.

**Comment by asiekierka** [comment]
Alright!

**Comment by asiekierka** [comment]
One last question: Does it happen without *Sponge*?

**Comment by Eufranio** [comment]
I couldn't test it yet, but it does **not** crash in the client (that doesn't have Sponge but has GC and FoamFix). I can test it later if you want.

**Comment by asiekierka** [comment]
Sure. Sponge and FoamFix both modify a fair amount of things in the engine, so it might be some kind of odd interaction.

**Comment by asiekierka** [comment]
I've found someone who has a similar problem without FoamFix *or* Sponge.

**Comment by asiekierka** [comment]
>Description: Watching Server

This pertains to the ServerHangWatchdog malfunctioning and *not* FoamFix, Sponge or Galacticraft.

Please set max-tick-time=0 as the *true* workaround and undo previous workarounds for the time being.
