### ISSUE TITLE
Crash with mekanism and foamfix

### ISSUE THREAD

**Issue by KristjanKr** [asiekierka/FoamFix#56]
Game crashes with latest mekanism and foamfix build, minecraft 1.11.2
Here is the crashlog: https://paste.ee/p/r1lLs
Mekanism version: Mekanism-1.11.2-9.3.1.305
Foamfix version: 0.6.3
Minecraft: 1.11.2
Forge: build 2315

**Comment by asiekierka** [comment]
>java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} to oak on block minecraft:log2, it is not an allowed value

>Many cases of this issue (1, 2) can be reproduced without FoamFix, so please make extra sure that it's FoamFix-specific!

Does it crash without FoamFix performing the same activity? The crash appears to be related to whatever provides "com.pengu.hcmb.recipe.RecipeCutMicroblock.func_77569_a" - Hammer Microblock, and looks like a genuine mistake in their code.
