### ISSUE TITLE
[Build from source 21eca96, 1.10.2] Crash at startup 

### ISSUE THREAD

**Issue by miuirussia** [asiekierka/FoamFix#59]
Crash not fixed:
[latest.txt](https://github.com/asiekierka/FoamFix/files/1075487/latest.txt)

**Comment by asiekierka** [comment]
Nope, I'm pretty sure this can't happen on the latest build.

**Comment by miuirussia** [comment]
But it happened

**Comment by asiekierka** [comment]
It did! I just got it reproduced. Sorry!
