### ISSUE TITLE
0.7.0 - issue

### ISSUE THREAD

**Issue by sylcai** [asiekierka/FoamFix#60]
No download available. That's an issue :p

**Comment by evernife** [comment]
http://asie.pl/Projects/Minecraft/Mods/FoamFix/
![image](https://user-images.githubusercontent.com/11357801/27249081-74516646-52e3-11e7-82fc-7bc588cfcbc6.png)

**Comment by evernife** [comment]
Seems legit

**Comment by evernife** [comment]
i am quite sure i deleted my comment that you are talking about 25 minuts ago '-'

**Comment by asiekierka** [comment]
I've documented the changes, but the release is not ready yet. Sorry - busy with finals!

**Comment by sylcai** [comment]
That's okay. Good luck with your finals! I hope you pass!
