### ISSUE TITLE
FoamFix broke on forge build 2363 1.12

### ISSUE THREAD

**Issue by loordgek** [asiekierka/FoamFix#62]
https://github.com/MinecraftForge/MinecraftForge/commit/dc043ac79f90a9b0da5efff64bb02a4a7301c242
2362 works fine

https://paste.ee/p/K4uK2

**Comment by asiekierka** [comment]
Yes, that would be related to my patches. Working on a fix!

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/commit/44735dd093320dbae85c77e7fbf8fafcdab65ac8
