### ISSUE TITLE
[1.10.2] FoamFix crash with 100~ mods

### ISSUE THREAD

**Issue by Migmag789** [asiekierka/FoamFix#65]
poof! crashes.
[crash-2017-07-10_21.44.37-client.txt](https://github.com/asiekierka/FoamFix/files/1136845/crash-2017-07-10_21.44.37-client.txt)

**Comment by asiekierka** [comment]
Try disabling parallel model baking.

**Comment by Migmag789** [comment]
What ? Can you give me this config please o.O ?

**Comment by asiekierka** [comment]
config/foamfix.cfg, experimental -> B:parallelModelBaking, set that to false

**Comment by Migmag789** [comment]
Okay, thank you :D
But ... is it likely to create RAM worries or not? Thank you anyway ! : D

**Comment by asiekierka** [comment]
No. Might make the game load 2-3 seconds slower, though.

**Comment by CocoVanChoco** [comment]
Im using FTB Sky Factory 3 + some Mods Updated and some added to the Pack
With Foamfix 0.6.3 and even with 0.7.2 Anarchy and Lawful im Getting a client Load Crash with the same Error the OP reported. 

Fun thing is, sometimes the Game start sometimes not and sometimes if i change some Settings in the Foamfix file it works again and then after aa Restart it wont for a few tries. 

It Happens only if Foamfix is active, if i remove Foamfix it works.

I also changed Forge and ForgeChunkloading config files wich was stated on Your website under Tipps.
Also i changed the tip on this Github with the Experimental change to false for the Parrallel Model Baking. As i said alreads. Sometimes the Game starts without a crash and sometimes it wont start and crash while Baking the Models.

**Comment by HenrikoMagnifico** [comment]
I tried disabling B:parallelModelBaking but it still crashed; https://pastebin.com/vc3gUwjA

**Comment by ohois** [comment]
I had the same problems. Since I disabled CodeChickenLib and CodeChickenCore and the mods that depend on them the crashes are gone.

**Comment by bochen415** [comment]
@HenrikoMagnifico that looks like the infamous milk bucket crash from MFR, can you disable milk buckets in MFR's config?
