### ISSUE TITLE
FoamFix 0.4.0 Anarchy Edition client crashed

### ISSUE THREAD

**Issue by TheMrCaveman** [asiekierka/FoamFix#7]
Minecraft 1.10.2
Forge 12.18.2.2171
FoamFix 0.4.0 Anarchy Edition

crash report: http://pastebin.com/G2s0cG5p

**Comment by asiekierka** [comment]
http://asie.pl/foamfix-0.4.0a-anarchy.jar

Does this help?

**Comment by TheMrCaveman** [comment]
No it still crashed

see report: http://pastebin.com/sJecgk6B

**Comment by asiekierka** [comment]
Wish I could reproduce it...

Try http://asie.pl/foamfix-0.4.0aa-anarchy.jar

**Comment by Joshwoo70** [comment]
same issue : https://gist.github.com/Joshwoo70/6247ed914161a88fb11bd079799588c9

**Comment by asiekierka** [comment]
Does it happen on Lawful?

2016-12-09 11:04 GMT+01:00 Josh <notifications@github.com>:

**Comment by Joshwoo70** [comment]
> Does it happen on Lawful?

Testing...

**Comment by TheMrCaveman** [comment]
http://pastebin.com/gkM6tDAW this is with 0.4.0aa-anarchy
lawful works fine

**Comment by asiekierka** [comment]
The official 0.4.0a on the website should work around this.

**Comment by TheMrCaveman** [comment]
Yes it works now, and a lot better then lawful. So thanks for fixing this!

**Comment by asiekierka** [comment]
>a lot better than lawful

Any data for this?
