### ISSUE TITLE
MC-1.12.1 Code Errors? 0.8.0 (1.12)b2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [asiekierka/FoamFix#70]
https://gist.github.com/P3rf3ctXZer0/383354b15946048e3c8e6d4e87697d3d

**Comment by asiekierka** [comment]
OutOfMemoryError.

**Comment by P3rf3ctXZer0** [comment]
@asiekierka Why did it still load fine then?

**Comment by asiekierka** [comment]
Might have managed to free a bit more memory later.
