### ISSUE TITLE
[1.10.2] [Spongeforge] Incompatibility

### ISSUE THREAD

**Issue by InjuredWolf** [asiekierka/FoamFix#72]
Running Foamfix on a spongeforge server causes it to crash due to FF transforming a class before SF can.

Log with crash: https://pastebin.com/zXq7AEh4

**Comment by asiekierka** [comment]
What version of FoamFix are you using?

(Generally, you may still run into issues later if you use FoamFix with SpongeForge anyway.)

**Comment by InjuredWolf** [comment]
tbh, don't actually know. the file I had didn't have a version in the filename - can't remember if that's normal or weird

EDIT: Nope, not normal. Don't know why I renamed it...

**Comment by liach** [comment]
It should be caused by some other coremods which implement IFMLLoadingPlugin and ModContainer together.

**Comment by asiekierka** [comment]
I think this has been fixed? Either way, Sponge is not supported.
