### ISSUE TITLE
[1.12.1] 0.8.0 beta 3 Causes Blocks from Immersive Engineering to become invisible

### ISSUE THREAD

**Issue by level555** [asiekierka/FoamFix#75]
FoamFix Version 0.8.3 beta 3 (both anarchy and lawful) causes various blocks from Immersive Engeneering including HV Wire Connectors, HV Wire Relay, steel cables between connectors, Wooden Storage Crates and some multiblocks (including the Metal Press and the Crusher to turn invisible.

0.7.4 doesn't have the issue

Withot Foamfix:
![2017-09-02_18 51 02](https://user-images.githubusercontent.com/5795889/29997307-2336e14a-9010-11e7-9dc0-33d7b69d270e.png)

With Foamfix 0.8.0 beta 3:
![2017-09-02_18 51 46](https://user-images.githubusercontent.com/5795889/29997309-388efc76-9010-11e7-9dce-d6077e404340.png)

log:

[fml-client-latest.txt](https://github.com/asiekierka/FoamFix/files/1272322/fml-client-latest.txt)

**Comment by asiekierka** [comment]
Bug in Immersive Engineering (not strictly a bug, rather a violation of the Set contract), will be fixed in a future release. Downgrade to 0.7.4 until that happens.
