### ISSUE TITLE
[1.12.1][0.8.0 beta 3 "Anarchy"] Immersive Engineering Textures disappear 

### ISSUE THREAD

**Issue by Kris1432** [asiekierka/FoamFix#76]
Version: 0.8.0 Beta 3 Anarchy
Forge: 2467

Issue: Textures are invisible: 
![image](https://user-images.githubusercontent.com/3301022/30002460-0ec13138-90a2-11e7-9347-01da249620d2.png)

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/75

**Comment by Kris1432** [comment]
woops, sorry
