### ISSUE TITLE
[1.12.1][no optifine] Some blocks of Immersive Engineering are invisible 

### ISSUE THREAD

**Issue by AndreiTS** [asiekierka/FoamFix#78]
with foamfix 0.8.0 beta3 anarchy:
![2017-09-07_11 19 33](https://user-images.githubusercontent.com/13489837/30168407-b0e4e1a6-93bf-11e7-97d4-7cdaf7bd4ae2.png)
![2017-09-07_11 33 08](https://user-images.githubusercontent.com/13489837/30168628-5df0faa6-93c0-11e7-8d03-04333a775e09.png)

with foamfix 0.7.4 anarchy:
![2017-09-07_11 36 23](https://user-images.githubusercontent.com/13489837/30168811-d9714a5a-93c0-11e7-8fa9-86678040c742.png)
![2017-09-07_11 25 58](https://user-images.githubusercontent.com/13489837/30168448-c8134c46-93bf-11e7-9ecd-c9b5919407cc.png)

**Comment by asiekierka** [comment]
https://github.com/asiekierka/FoamFix/issues/77
