### ISSUE TITLE
[idea] backport tile entity unloading fix

### ISSUE THREAD

**Issue by liach** [asiekierka/FoamFix#79]
https://github.com/MinecraftForge/MinecraftForge/issues/4386#issuecomment-328295339

Compared to the old fix from mezz which is Java 8 only for its use of `Collection#removeIf`, this fix uses `Collection#removeAll(Collection)` that has a similar performance, although requiring to create a new collection every time (Minecraft's bad code is doing that a lot already, why should we mind it?). As a result, this fix may be ported by foamfix to minecraft 1.10 and 1.11, saving the lives of the players.

**Comment by asiekierka** [comment]
@liach I don't think we mind Java 8 too much, seeing as many 1.7+ mods depend on it anyway.

Does that change your proposal of the fix?

As for the backport, sure, I don't mind. How many Minecraft versions does it affect?

**Comment by asiekierka** [comment]
@liach I poked mezz about it, and if it's an issue on 1.10/1.11 we may see it backported by Forge after all.

**Comment by liach** [comment]
I think it affects all minecraft versions. Ever since I started modding in 1.7, the way minecraft removes tile entities is always through removing items in a list.

**Comment by liach** [comment]
Guess I need to ask player to add this feature to fastcraft, too, if he likes.

**Comment by liach** [comment]
Closing since mezz has ported.
