### ISSUE TITLE
Idea? Optional feature? Crazyness?

### ISSUE THREAD

**Issue by sefldron** [asiekierka/FoamFix#81]
Add a single player feature to affect world unloading and loading upon starting and ending a world. 
 Feature would add a small amount to loading up and exiting time but allow running of a type of kill all command when exiting a game. During the Purging process entity cords will be saved and referenced to the generic name. On reload this world specific text file will be referenced effectively respawning in all entities as the same type that they were before. Sure some features may be different (armor, weapon etc.) But it could theoretically clean up saved worlds and make loading cleaner. Respawning of entities could even be delayed and configured in to player spawning effectively delaying the initial spawning into the world, smoothing it out along side of the version checking cycle of all mods. By far a very laggy moment in modded Minecraft gameplay that can cause ticking lag too. 

  Another idea is to identify the process that causes the game to progress into the future during a lag Spike (even for the beast CPU I'm sure this happens from time to time.) Allow a pass through that allows the game to "skip" the ticks that it is forcing but not allow any actual game time or any events to actually take place. (Removing the "death" from the Spike) 
 No more over 9000 fully automatic skeleton machine gun attacks in the forest. Ugh.

  I know that there is dynamic tick rate but that only alters actively ticking rendered situations I believe?? 
 I could not get that one to work for me for some reason.

      Thanks for letting me share.

**Comment by asiekierka** [comment]
The first idea is outside the scope of FoamFix.

>Allow a pass through that allows the game to "skip" the ticks that it is forcing but not allow any actual game time or any events to actually take place. (Removing the "death" from the Spike)

The second idea is impossible to cleanly separate.
