### ISSUE TITLE
0.8.0 in 1.12.2 - Faster Hopper causes new hopper misbehavior

### ISSUE THREAD

**Issue by zontargs** [asiekierka/FoamFix#82]
When faster hopper is enabled, hoppers being powered and unpowered take noticeably longer to start accepting items from inventories above them after becoming unpowered (which breaks timings), and closes the hopper inventory screen each time the hopper's power state changes.

This is easy to reproduce when a hopper is feeding a dropper being run off a clock, when the hopper itself is also being powered/unpowered by the clock. The hopper is slowed down to the point that the dropper goes empty, and the hopper inventory screen is almost immediately closed when the clock is running.

This misbehavior disappears if Faster Hopper is disabled. BetterFPS's hopper optimizations do not influence this issue.

**Comment by zlainsama** [comment]
I can confirm this issue too. This also happens in 1.12.1.
I was using hopper to make botania mana generation, but my fuels keep disappearing.
And i found out the hopper's inventory is not saved during redstone power state changes.
Then i found out it was FoamFix causeing it. I didn't test any further.
I guess i will disable FasterHopper for now.

Edit: my test was
   1) place a hooper pointing nowhere
   2) put some items in it
   3) place a redstone torch to power it
   4) check the hopper's inventory

**Comment by zontargs** [comment]
Oh geez, it DOES delete the entire inventory if the power state changes in 1.12.2 as well. I didn't notice because it was hooked up to a lava incinerator.

**Comment by asiekierka** [comment]
Ouch, sorry!

http://asie.pl/files/minecraft/foamfix-0.8.1-beta1-1.12-anarchy.jar

Please try this one!

**Comment by zontargs** [comment]
Much better! Looks like it fixed all the reported issues with the Faster Hopper.

**Comment by asiekierka** [comment]
Alright, I'll push a release with this fix soon. Sorry once again!

**Comment by zlainsama** [comment]
Thank you for your wonderful work.
