### ISSUE TITLE
Request - Add feature for 1.12.2 Forge 93 (Disable Moved Too Quickly)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [asiekierka/FoamFix#83]
I have a modpack that is private that has many mods and they all play nice but lately due to tick count I am getting a Username moved too quickly and was removed from game. I know its not productive to ignore a possible leak but I really like the mods I have and want to keep all of them. So can you please help me with this? @asiekierka

**Comment by P3rf3ctXZer0** [comment]
@https://www.reddit.com/r/feedthebeast/comments/5vke0i/looking_for_mod_to_stop_player_moved_too_quickly/

Its at a core level ergo requires mod intervention.

This mod used to exist but no source code or anything so I am without help
https://minecraft.curseforge.com/projects/mtqfix

I used to use it to prevent being wrongfully kicked back in the day on my 1.10.2 server.

**Comment by unascribed** [comment]
For now, here's a one-off mod I slapped together for a similar reason: https://unascribed.com/f/722eb593_NoMTQ-1.11.2-1.2.jar

And here's a 1.12 port I made just now (untested, just compiled the 1.11 version for 1.12, should work though): https://unascribed.com/f/f4daf825_NoMTQ-1.12.1-1.3.jar

**Comment by exaskye** [comment]
This is outside the scope of FoamFix.

**Comment by P3rf3ctXZer0** [comment]
Sadness

**Comment by asiekierka** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4526
