### ISSUE TITLE
Main Site is Down?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [asiekierka/FoamFix#87]
![2017-10-22 21_52_27-steam](https://user-images.githubusercontent.com/10351221/31870397-6596db46-b773-11e7-84c9-e5f734ede8b0.png)

**Comment by exaskye** [comment]
asie's site will probably be down for a while, in the mean time you can look at my [unofficial builds](https://unascribed.com/foamfix).

**Comment by P3rf3ctXZer0** [comment]
His site is also virused ... you should warn users. When I mean virused I mean loading the page tries to do a few things like change default search engine plus Sets the bookmarks seen in that image

**Comment by exaskye** [comment]
I'm pretty sure your *computer* has a virus, asie's site is entirely harmless. There's not a single script on that page. Either way, a webpage can't set bookmarks or change your search engine.

It looks like you have university spyware installed, so that's my first guess.

**Comment by MaciejMalczyk** [comment]
@unascribed Any 1.7.10 builds ?

**Comment by exaskye** [comment]
...no? FoamFix isn't useful on 1.7.
