### ISSUE TITLE
Crash on breaking blocks

### ISSUE THREAD

**Issue by Flashwar** [asiekierka/FoamFix#89]
When destroying a campfire von TaN, the game crash, with the following error
Crashlog: https://pastebin.com/CYS3k1Sz

**Comment by exaskye** [comment]
This is probably not a FoamFix issue. Please try to reproduce it without FoamFix.

**Comment by Flashwar** [comment]
Without FoamFix it doesn´t crash anymore

**Comment by exaskye** [comment]
This issue shouldn't have been closed; I didn't respond as I had nothing to add and don't currently have time to attempt to reproduce the issue.
