### ISSUE TITLE
New "fasterAnimation" Option causes constant stuttering [0.8.2-1.12.2]

### ISSUE THREAD

**Issue by FizzBuzz3000** [asiekierka/FoamFix#92]
So after updating to save that sweet, sweet 10% ram, the game constantly stutters with the new "fasterAnimation" option enabled. With it disabled my FPS is stable and everything just werks™

With it enabled:
![image](https://cdn.discordapp.com/attachments/326418584450367489/384099370179624960/image.png)

**Comment by asiekierka** [comment]
Try decreasing the mipmap level for animations specifically. Does that lower the stuttering?

(Also, out of curiosity alone, is the overall FPS higher?)

**Comment by sandalle** [comment]
My OS X box (High Sierra OS X, ATI Radeon R9 M370X, Oracle Java 1.8.0_152 x86_64) works fine with `B:fasterAnimation=true` and `I:maxAnimationMipLevel=-1`, but on my Linux Mint 18.2 x86_64 box (NVIDIA Corporation GM204M [GeForce GTX 970M] (rev a1) with proprietary driver 384.90-0ubuntu0.16.04.1, Oracle Java 1.8.0_111, x86_64) I get 0 FPS as reported by F3 in-game on both SSP and SMP. If I set `B:fasterAnimation=false`, I have my normal FPS back. I also tried the following values for `I:maxAnimationMipLevel`: `4`, `3`, `2`, `1`, and `0` along with `B:fasterAnimation=true` and had 0 FPS as the result.

Minecraft: 1.12.2
Forge Mod Loader: 1.12.2-14.23.1.2556
FoamFix:  0.8.2-1.12.2-anarchy

Allocated RAM for both is 6G to Java with plenty of headroom for the OS leftover.

**Comment by asiekierka** [comment]
So the proprietary nVidia driver doesn't like it. As far as I know, it does help on AMD, though. Hmm.

**Comment by asiekierka** [comment]
Worked around in the latest commit by enabling it on AMD cards only. I need to debug it on nVidia further, but I'll push a release now.

**Comment by sandalle** [comment]
Works on both my AMD (OS X) and nVidia (Linux Mint) machines with `I:fasterAnimation=1`, thanks!

**Comment by asiekierka** [comment]
@sandalle Yeah. It's more of a workaround (still have to figure out why it slows down the game on nVidia specifically), but it works fine!
