### ISSUE TITLE
[1.12.2] Crash with TexFix on World load

### ISSUE THREAD

**Issue by MasterEnderman** [asiekierka/FoamFix#96]
Just created a new world.

Forge: 14.23.1.2562
FoamFix: 0.8.2 (Anarchy)
Crashreport: https://pastebin.com/Lc6bpHWm

The world loads fine after i removed TexFix by Speiger.

**Comment by asiekierka** [comment]
This is a TexFix bug. As a workaround, you can disable dynamicItemModels - however, that may only be beneficial on ~128x and higher texture packs - I cannot promise it to be, tests would have to be made and my current hardware cannot handle packs that large. On lower packs, I definitely recommend removing TexFix.

**Comment by Speiger** [comment]
On bigger packs with a lot of textures it still has an effect even on 16x but yeah I will look into that.

**Comment by asiekierka** [comment]
@Speiger The effect of dynamicItemModels scales with the amount of item models, and so - to some extent - with the amount of textures. Your mod would only then have a benefit on packs in which the amount of block textures greatly outweighs the amount of item models.

I told you to add a compatibility option that only cleans the miplevels. I did so myself, but you didn't like that; now you probably won't do so yourself. :V

**Comment by Speiger** [comment]
Actually the mod should generate the array, I check that out when I am home again.
