### ISSUE TITLE
[1.12.2]  Foamfix conflict with Better Foliage

### ISSUE THREAD

**Issue by Endmateria** [asiekierka/FoamFix#98]
When Foamfix and Better Foliage are installed together, they crash the game clientside. 
 https://gist.github.com/Endmateria/7e6a26f106895df74830dd84575d4835#file-crash-2017-12-14_22-59-45-client-txt

MC 1.12.2
Forge 1.12.2 -14.23.1.2566
Foamfix 0.8.2 Anarchy
Better Foliage 1.12 - 2.1.10

-no other mods installed
-same version of Better Foliage does not crash with Foamfix 0.8.1 Anarchy

**Comment by Endmateria** [comment]
@octarine-noise

**Comment by asiekierka** [comment]
Fixed already. https://asie.pl/files/mods/FoamFix/foamfix-0.8.3-1.12.2-anarchy.jar
