### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by davqvist** [asiekierka/FoamFix#99]
https://pastebin.com/qdxaf7tM

Foamfix 0.8.3-anarchy
Forge 2578

Reverting Forge version to older version fixes the issue.

**Comment by asiekierka** [comment]
Does removing FoamFix?

**Comment by davqvist** [comment]
I have not tested, sorry, already reverted my pack to Forge 2561.
I will report when I have time

**Comment by ImAK9** [comment]
I can confirm this happens to me too on the latest 1.12.2 forge version 2578

**Comment by asiekierka** [comment]
Does removing FoamFix help?

**Comment by bs2609** [comment]
There's a known [issue](https://github.com/BluSunrize/ImmersiveEngineering/issues/2672) with Immersive Engineering, which probably is the cause here.

**Comment by katur239** [comment]
Removing FoamFix doesn't remove the error. On Forge 2570 it'll boot but give this error in the console.

`java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: pl.asie.foamfix.common.FoamyBlockState.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z`

Removing FoamFix again just throws a vanilla error instead.

**Comment by asiekierka** [comment]
'k, thanks. So it's not my fault.
